import {
  Type,
  Hash,
  Shield,
  Heart,
  Percent,
  Calendar,
  Banknote,
  ArrowLeftRight,
  CaseSensitive,
  Palette,
  Braces,
} from "lucide-react";
import { type LucideIcon } from "lucide-react";

export interface ToolDef {
  id: string;
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  category: string;
  icon: LucideIcon;
  keywords: string[];
  metaTitle: string;
  metaDescription: string;
  primaryKeyword: string;
  howToUse: string[];
  faq: { question: string; answer: string }[];
}

export const toolCategories = [
  { id: "text", name: "Text Tools", color: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300" },
  { id: "math", name: "Math & Finance", color: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300" },
  { id: "dev", name: "Developer Tools", color: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300" },
  { id: "converter", name: "Converters", color: "bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300" },
];

export const tools: ToolDef[] = [
  {
    id: "word-counter",
    name: "Word Counter",
    shortName: "Word Count",
    description: "Count words, characters, sentences, and paragraphs instantly.",
    longDescription: "Free online word counter tool. Instantly count words, characters (with and without spaces), sentences, paragraphs, and estimated reading time. Perfect for writers, students, bloggers, and SEO professionals who need to meet specific word count requirements.",
    category: "text",
    icon: Type,
    keywords: ["word counter", "character counter", "word count tool", "online word counter", "text counter", "sentence counter", "reading time calculator"],
    metaTitle: "Free Word Counter - Count Words, Characters & Reading Time",
    metaDescription: "Count words, characters, sentences and reading time instantly. Free online word counter for writers, students and SEO professionals. No sign-up.",
    primaryKeyword: "word counter",
    howToUse: ["Type or paste your text into the text area above.", "View real-time counts for words, characters, sentences, and paragraphs.", "Check the keyword density section to see your most used words.", "Use the reading time estimate to plan your content."],
    faq: [
      { question: "How does the word counter count words?", answer: "The word counter splits your text by whitespace and counts each group as one word. It handles multiple spaces, tabs, and line breaks correctly." },
      { question: "How is reading time calculated?", answer: "Reading time is estimated based on an average reading speed of 200 words per minute, which is the standard for adult readers." },
      { question: "Does the word counter count numbers?", answer: "Yes, any group of characters separated by spaces is counted as a word, including numbers and mixed alphanumeric strings." },
    ],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    shortName: "Password Gen",
    description: "Generate strong, secure passwords with customizable options.",
    longDescription: "Generate strong, secure, and random passwords instantly. Customize length, include uppercase, lowercase, numbers, and special characters. Check password strength in real-time. Perfect for creating secure passwords for all your online accounts.",
    category: "dev",
    icon: Shield,
    keywords: ["password generator", "strong password", "secure password", "random password", "password maker", "create password"],
    metaTitle: "Free Password Generator - Create Strong Secure Passwords",
    metaDescription: "Generate strong, secure passwords instantly. Customize length and characters. Check password strength. Free online tool, no data stored.",
    primaryKeyword: "password generator",
    howToUse: ["Adjust the password length using the slider (4 to 64 characters).", "Toggle character types: uppercase, lowercase, numbers, and symbols.", "Click 'Generate New Password' to create a fresh password.", "Click the copy icon to copy the password to your clipboard."],
    faq: [
      { question: "Are the generated passwords truly random?", answer: "Yes, we use the Web Crypto API (crypto.getRandomValues) which provides cryptographically secure random numbers." },
      { question: "How long should my password be?", answer: "We recommend at least 12 characters for strong security. Longer passwords with mixed character types are significantly harder to crack." },
      { question: "Are my passwords stored anywhere?", answer: "No. Passwords are generated entirely in your browser and are never sent to any server. Once you navigate away, the password is gone." },
    ],
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    shortName: "BMI Calc",
    description: "Calculate your Body Mass Index and see your health category.",
    longDescription: "Calculate your Body Mass Index (BMI) quickly and accurately. Enter your height and weight to find out if you're underweight, normal weight, overweight, or obese. Includes BMI chart and health category explanations for better understanding of your results.",
    category: "math",
    icon: Heart,
    keywords: ["bmi calculator", "body mass index", "bmi checker", "healthy weight", "bmi chart", "weight calculator"],
    metaTitle: "Free BMI Calculator - Calculate Body Mass Index Online",
    metaDescription: "Calculate your BMI instantly with metric or imperial units. Free online BMI calculator with health categories and visual chart. No sign-up required.",
    primaryKeyword: "BMI calculator",
    howToUse: ["Select your preferred unit system (Metric or Imperial).", "Enter your weight and height in the fields provided.", "Click 'Calculate BMI' to see your results.", "Review the BMI scale and health category for context."],
    faq: [
      { question: "What is a healthy BMI range?", answer: "A BMI between 18.5 and 24.9 is considered normal weight. Below 18.5 is underweight, 25-29.9 is overweight, and 30 or above is classified as obese." },
      { question: "Is BMI accurate for everyone?", answer: "BMI is a useful screening tool but has limitations. It doesn't account for muscle mass, bone density, age, sex, or body composition. Athletes may have a high BMI due to muscle mass." },
      { question: "How is BMI calculated?", answer: "BMI is calculated by dividing your weight in kilograms by the square of your height in meters: BMI = weight (kg) / height (m) squared." },
    ],
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    shortName: "Percentage",
    description: "Calculate percentages, percentage change, and percentage difference.",
    longDescription: "Calculate any percentage easily with multiple calculation modes. Find what percent of a number is, calculate percentage increase or decrease, and find the percentage difference between two numbers. Essential for students, business owners, and financial calculations.",
    category: "math",
    icon: Percent,
    keywords: ["percentage calculator", "percent calculator", "percentage increase", "percentage decrease", "percent of", "calculate percentage"],
    metaTitle: "Free Percentage Calculator - Calculate Percentages Instantly",
    metaDescription: "Calculate percentages, increase, decrease and change instantly. Free online percentage calculator for students, business and finance. Works in browser.",
    primaryKeyword: "percentage calculator",
    howToUse: ["Choose a calculation mode: '% of Number', '% of What?', or '% Change'.", "Enter your numbers in the input fields.", "Click 'Calculate' to see the result instantly.", "Use the common examples below for quick reference."],
    faq: [
      { question: "How do I calculate percentage increase?", answer: "Use the '% Change' tab. Enter the original value in 'From' and the new value in 'To'. The calculator shows the percentage increase or decrease." },
      { question: "What is 10% of 500?", answer: "10% of 500 is 50. You can verify this using the '% of Number' tab: enter 10 in the percentage field and 500 in the number field." },
      { question: "How do I calculate what percentage one number is of another?", answer: "Use the '% of What?' tab. Enter the part in the first field and the whole in the second field. For example, 50 is 25% of 200." },
    ],
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    shortName: "Age Calc",
    description: "Calculate your exact age in years, months, and days.",
    longDescription: "Calculate your exact age in years, months, weeks, days, hours, minutes, and seconds. Simply enter your date of birth and get a detailed breakdown of your age. Also calculates days until your next birthday.",
    category: "math",
    icon: Calendar,
    keywords: ["age calculator", "calculate age", "how old am I", "age in days", "birthday calculator", "date of birth calculator"],
    metaTitle: "Free Age Calculator - Exact Age in Years, Months & Days",
    metaDescription: "Calculate your exact age in years, months, days, hours and seconds. Free online age calculator with next birthday countdown and zodiac sign.",
    primaryKeyword: "age calculator",
    howToUse: ["Enter your date of birth in the first date field.", "Optionally change the 'Age at Date' to calculate age at a specific point.", "Click 'Calculate Age' to see a detailed age breakdown.", "View your zodiac sign, day of birth, and next birthday countdown."],
    faq: [
      { question: "How accurate is the age calculator?", answer: "The age calculator is accurate to the day, accounting for leap years and varying month lengths. It shows your exact age in multiple units." },
      { question: "Does it account for leap years?", answer: "Yes, the calculator properly handles leap years when computing your exact age in days, weeks, and months." },
      { question: "Can I calculate age between two custom dates?", answer: "Yes! Change the 'Age at Date' field to any date to calculate the age difference between your birth date and that specific date." },
    ],
  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    shortName: "Loan Calc",
    description: "Calculate monthly payments, total interest, and amortization.",
    longDescription: "Calculate your monthly loan payments, total interest paid, and view a complete amortization schedule. Works for mortgages, car loans, personal loans, and any fixed-rate loan. Adjust interest rate, loan term, and principal to find the perfect loan for your budget.",
    category: "math",
    icon: Banknote,
    keywords: ["loan calculator", "mortgage calculator", "emi calculator", "monthly payment", "interest calculator", "amortization schedule"],
    metaTitle: "Free Loan Calculator - Monthly Payment & Amortization",
    metaDescription: "Calculate monthly loan payments, total interest and view amortization schedule. Free mortgage and EMI calculator. Works for any fixed-rate loan.",
    primaryKeyword: "loan calculator",
    howToUse: ["Enter the total loan amount in dollars.", "Enter the annual interest rate as a percentage (e.g., 6.5 for 6.5%).", "Enter the loan term in years.", "Click 'Calculate Payment' to see monthly payment, total cost, and full amortization schedule."],
    faq: [
      { question: "What types of loans does this calculator work for?", answer: "This calculator works for any fixed-rate loan including mortgages, car loans, personal loans, student loans, and business loans." },
      { question: "How is the monthly payment calculated?", answer: "The monthly payment is calculated using the standard amortization formula: M = P[r(1+r)^n]/[(1+r)^n-1], where P is principal, r is monthly rate, and n is total months." },
      { question: "What is an amortization schedule?", answer: "An amortization schedule shows how each monthly payment is split between principal and interest over the life of the loan, plus the remaining balance after each payment." },
    ],
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    shortName: "Unit Convert",
    description: "Convert between units of length, weight, temperature, and more.",
    longDescription: "Convert between hundreds of units across multiple categories including length, weight, temperature, volume, area, speed, time, and data. Fast, accurate, and easy to use unit conversion tool for students, professionals, and everyday use.",
    category: "converter",
    icon: ArrowLeftRight,
    keywords: ["unit converter", "length converter", "weight converter", "temperature converter", "metric converter", "measurement converter"],
    metaTitle: "Free Unit Converter - Length, Weight, Temperature & More",
    metaDescription: "Convert between units of length, weight, temperature, volume, speed and data storage. Free online unit converter. Metric and imperial supported.",
    primaryKeyword: "unit converter",
    howToUse: ["Select a category (Length, Weight, Temperature, Volume, Area, Speed, or Data).", "Choose the unit you're converting from and to using the dropdowns.", "Enter a value in the 'From' field — the 'To' field updates instantly.", "Click the swap button to reverse the conversion direction."],
    faq: [
      { question: "How many unit categories are available?", answer: "There are 7 categories: Length, Weight, Temperature, Volume, Area, Speed, and Data Storage. Each category has multiple units to convert between." },
      { question: "Is the unit converter accurate?", answer: "Yes, conversions use precise mathematical factors. For example, 1 inch equals exactly 2.54 centimeters, and temperature conversions use the exact Celsius-Fahrenheit formulas." },
      { question: "Can I convert between metric and imperial?", answer: "Absolutely! The converter supports both metric (km, kg, Celsius) and imperial (miles, pounds, Fahrenheit) systems and converts between them seamlessly." },
    ],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    shortName: "Case Convert",
    description: "Convert text to uppercase, lowercase, title case, and more.",
    longDescription: "Instantly convert your text between different cases including uppercase, lowercase, title case, sentence case, camelCase, PascalCase, snake_case, and kebab-case. Perfect for developers, writers, and anyone who needs to format text quickly.",
    category: "text",
    icon: CaseSensitive,
    keywords: ["case converter", "uppercase converter", "lowercase converter", "title case", "sentence case", "text case changer"],
    metaTitle: "Free Case Converter - Uppercase, Title Case, camelCase & More",
    metaDescription: "Convert text to uppercase, lowercase, title case, camelCase, snake_case and more. Free online case converter. Copy results instantly.",
    primaryKeyword: "case converter",
    howToUse: ["Type or paste your text into the input area.", "Click any conversion button (UPPERCASE, lowercase, Title Case, etc.).", "The converted text appears in the result section below.", "Click 'Copy' to copy the converted text to your clipboard."],
    faq: [
      { question: "What is camelCase?", answer: "camelCase starts with a lowercase letter and each subsequent word starts with an uppercase letter with no spaces. Example: 'helloWorld'. Commonly used in JavaScript and Java." },
      { question: "What is the difference between Title Case and Sentence case?", answer: "Title Case capitalizes the first letter of every word (Hello World), while Sentence case only capitalizes the first letter of the sentence (Hello world)." },
      { question: "What is snake_case used for?", answer: "snake_case uses underscores between words with all lowercase letters (hello_world). It's commonly used in Python, Ruby, and database column names." },
    ],
  },
  {
    id: "color-picker",
    name: "Color Picker",
    shortName: "Color Pick",
    description: "Pick colors and convert between HEX, RGB, and HSL formats.",
    longDescription: "Pick any color and instantly get its values in HEX, RGB, HSL, and CMYK formats. Use the color wheel or input specific values. Generate color palettes and find complementary colors. Essential tool for designers, developers, and artists.",
    category: "dev",
    icon: Palette,
    keywords: ["color picker", "hex color", "rgb color", "hsl color", "color converter", "color palette generator"],
    metaTitle: "Free Color Picker - HEX, RGB, HSL Converter & Palette Tool",
    metaDescription: "Pick colors and convert between HEX, RGB, HSL formats instantly. Free online color picker with palette generator for designers and developers.",
    primaryKeyword: "color picker",
    howToUse: ["Use the HEX input to enter a color code directly, or adjust the RGB/HSL sliders.", "Click any color value (HEX, RGB, HSL) to copy it to your clipboard.", "View color variations: lighter, darker, and complementary colors.", "Use the generated palette at the bottom for shading inspiration."],
    faq: [
      { question: "What is the difference between HEX and RGB?", answer: "HEX is a hexadecimal color code (e.g., #FF5733) commonly used in web design. RGB represents color as three numbers (e.g., 255, 87, 51) representing red, green, and blue intensity." },
      { question: "What is HSL color format?", answer: "HSL stands for Hue (0-360 degrees on the color wheel), Saturation (0-100% intensity), and Lightness (0-100% brightness). It's more intuitive for adjusting colors." },
      { question: "How do I find a complementary color?", answer: "A complementary color is automatically calculated and shown in the Color Variations section. It's the color directly opposite on the color wheel, creating high contrast." },
    ],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    shortName: "JSON Format",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    longDescription: "Format, validate, and beautify your JSON data instantly. Paste messy JSON and get perfectly formatted, indented output with syntax highlighting. Includes error detection, JSON minification, and tree view. Essential tool for developers working with APIs and data.",
    category: "dev",
    icon: Braces,
    keywords: ["json formatter", "json beautifier", "json validator", "json viewer", "format json", "pretty print json"],
    metaTitle: "Free JSON Formatter & Validator - Beautify JSON Online",
    metaDescription: "Format, validate and beautify JSON instantly with syntax highlighting. Free online JSON formatter with tree view and minifier. 100% private.",
    primaryKeyword: "JSON formatter",
    howToUse: ["Paste your JSON data into the input text area, or click 'Upload .json' to load a file.", "Click 'Format / Beautify' to pretty-print the JSON with proper indentation.", "Click 'Minify' to compress JSON to a single line.", "Click 'Validate' to check if your JSON is valid without reformatting."],
    faq: [
      { question: "What is JSON?", answer: "JSON (JavaScript Object Notation) is a lightweight data-interchange format that's easy for humans to read and write, and easy for machines to parse and generate. It's used widely in APIs and configuration files." },
      { question: "Why is my JSON showing an error?", answer: "Common JSON errors include missing commas between items, trailing commas (not allowed in JSON), unquoted keys, and single quotes instead of double quotes. The error message will tell you exactly where the problem is." },
      { question: "Is my JSON data sent to a server?", answer: "No. All JSON processing happens entirely in your browser. Your data is never transmitted to any external server, ensuring complete privacy." },
    ],
  },
];