import {
  Type,
  Hash,
  Shield,
  Heart,
  Percent,
  Calendar,
  Banknote,
  ArrowLeftRight,
  CaseSensitive,
  Palette,
  Braces,
  ImageDown,
  QrCode,
  Binary,
  Link,
  FileText,
  AlignLeft,
  Lock,
  Diff,
  FileDown,
  TextCursorInput,
} from "lucide-react";
import { type LucideIcon } from "lucide-react";

export interface ToolDef {
  id: string;
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  category: string;
  icon: LucideIcon;
  keywords: string[];
  metaTitle: string;
  metaDescription: string;
  primaryKeyword: string;
  howToUse: string[];
  faq: { question: string; answer: string }[];
  features: string[];
  examples: { input: string; output: Record<string, string> };
}

export const toolCategories = [
  { id: "text", name: "Text Tools", color: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300" },
  { id: "math", name: "Math Calculators", color: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300" },
  { id: "dev", name: "Developer Tools", color: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300" },
  { id: "image", name: "Image Tools", color: "bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300" },
];

export const tools: ToolDef[] = [
  {
    id: "word-counter",
    name: "Word Counter",
    shortName: "Word Count",
    description: "Count words, characters, sentences, and paragraphs instantly.",
    longDescription: "Free online word counter tool. Instantly count words, characters (with and without spaces), sentences, paragraphs, and estimated reading time. Perfect for writers, students, bloggers, and SEO professionals who need to meet specific word count requirements.",
    category: "text",
    icon: Type,
    keywords: ["word counter", "character counter", "word count tool", "online word counter", "text counter", "sentence counter", "reading time calculator"],
    metaTitle: "Free Word Counter \u2013 Count Words, Characters & Reading Time",
    metaDescription: "Count words, characters, sentences and reading time instantly. Free online word counter for writers, students and SEO professionals. No sign-up.",
    primaryKeyword: "word counter",
    howToUse: ["Type or paste your text into the text area above.", "View real-time counts for words, characters, sentences, and paragraphs.", "Check the keyword density section to see your most used words.", "Use the reading time estimate to plan your content."],    faq: [
      { question: "What is a Word Counter?", answer: "A word counter is a free online tool that instantly counts the total number of words, characters, sentences, and paragraphs in any text you paste or type. It also estimates reading and speaking time, making it essential for writers, students, bloggers, and SEO professionals who need to meet specific word count requirements." },
      { question: "How are words counted?", answer: "The word counter splits your text by whitespace (spaces, tabs, and line breaks) and counts each contiguous group of non-whitespace characters as one word. It correctly handles multiple spaces between words, trailing and leading spaces, and mixed punctuation so every word is counted accurately." },
      { question: "Does punctuation count as a word or character?", answer: "Punctuation marks are counted as characters but never as separate words. For example, \"Hello!\" counts as one word and six characters (H-e-l-l-o-!). The word counter is smart enough to keep punctuation attached to the word it follows." },
      { question: "Can I upload a file to count words?", answer: "Currently the word counter works with text you paste or type directly into the text area. You can copy text from any document (Word, Google Docs, PDF) and paste it in. File upload support may be added in a future update." },
      { question: "Is my text stored or sent to a server?", answer: "No. All counting happens entirely in your browser using JavaScript. Your text is never uploaded, stored, or transmitted to any server. Once you close or refresh the page, your text is completely gone." },
      { question: "Does the word counter work offline?", answer: "Yes, once the page has loaded, the word counter works completely offline. All the counting logic runs in your browser with no internet connection required. You can even use it in airplane mode after the initial page load." },
    ],
    features: ["Word Count", "Character Count (with/without spaces)", "Sentence Count", "Paragraph Count", "Reading Time Estimate", "Speaking Time Estimate", "Keyword Density Analysis"],
    examples: { input: "Hello World! This is a sample text for the word counter tool.", output: { Words: "12", Characters: "61", Sentences: "1", "Reading Time": "6 sec" } },
  },
  {
    id: "character-counter",
    name: "Character Counter",
    shortName: "Char Count",
    description: "Count characters, analyze frequency, and get detailed text composition stats.",
    longDescription: "Count characters with and without spaces, analyze character frequency distribution, and get a detailed breakdown of your text composition including letters, numbers, spaces, and special characters. Perfect for Twitter/X posts, SMS messages, meta descriptions, and any content with character limits.",
    category: "text",
    icon: TextCursorInput,
    keywords: ["character counter", "letter counter", "character count", "text analysis", "character frequency", "char counter", "text composition"],
    metaTitle: "Free Character Counter \u2013 Count Characters & Analyze Text",
    metaDescription: "Count characters, analyze frequency and get text composition stats instantly. Free online character counter for social media, SMS and SEO. No sign-up.",
    primaryKeyword: "character counter",
    howToUse: ["Type or paste your text into the text area.", "View real-time character counts including total, without spaces, and unique characters.", "Check the character density breakdown to see letters, numbers, spaces, and special characters.", "Review the top 10 most-used characters with frequency percentages."],    faq: [
      { question: "What is a Character Counter?", answer: "A character counter is a free online tool that counts the total number of characters in your text, including or excluding spaces. It also provides a detailed breakdown of character types \u2014 letters, numbers, spaces, and special characters \u2014 along with frequency analysis of your most-used characters." },
      { question: "How does the character frequency analysis work?", answer: "The tool scans your entire text and tallies every occurrence of each unique character. It then ranks characters by frequency and shows the top 10 most-used characters with both their raw count and percentage of total characters, helping you spot overused characters or unusual patterns." },
      { question: "Does it count hidden characters like tabs and line breaks?", answer: "Yes. The total character count includes all whitespace characters \u2014 spaces, tabs, and line breaks. The \"without spaces\" count strips all whitespace so you can see only the visible, printable characters." },
      { question: "Can I use this for social media character limits?", answer: "Absolutely. The character counter is perfect for checking if your text fits within platform limits \u2014 Twitter/X (280 characters), Instagram bio (150 characters), SMS messages (160 characters), Google meta descriptions (160 characters), and more. Use the \"without spaces\" count if the platform does not count spaces." },
      { question: "Is my text stored anywhere?", answer: "No. All processing happens entirely in your browser. Your text is never sent to any server or stored anywhere. When you close the tab, your text is gone forever." },
      { question: "Does it work offline?", answer: "Yes. Once the page has loaded in your browser, the character counter works completely offline with no internet connection needed. All counting and analysis runs locally using JavaScript." },
    ],
    features: ["Total Character Count", "Characters Without Spaces", "Character Frequency Analysis", "Letter/Number/Space/Special Breakdown", "Unique Character Count", "Copy Stats to Clipboard"],
    examples: { input: "Hello World", output: { Characters: "11", "Without Spaces:": "10", Letters: "10", "Spaces": "1" } },
  },
  {
    id: "password-generator",
    name: "Password Generator",
    shortName: "Password Gen",
    description: "Generate strong, secure passwords with customizable options.",
    longDescription: "Generate strong, secure, and random passwords instantly. Customize length, include uppercase, lowercase, numbers, and special characters. Check password strength in real-time. Perfect for creating secure passwords for all your online accounts.",
    category: "dev",
    icon: Shield,
    keywords: ["password generator", "strong password", "secure password", "random password", "password maker", "create password"],
    metaTitle: "Free Password Generator – Create Strong Secure Passwords",
    metaDescription: "Generate strong, secure passwords instantly. Customize length and characters. Check password strength. Free online tool, no data stored.",
    primaryKeyword: "password generator",
    howToUse: ["Adjust the password length using the slider (4 to 64 characters).", "Toggle character types: uppercase, lowercase, numbers, and symbols.", "Click 'Generate New Password' to create a fresh password.", "Click the copy icon to copy the password to your clipboard."],    faq: [
      { question: "What is a Password Generator?", answer: "A password generator is a free online tool that creates strong, random passwords using cryptographically secure algorithms. You can customize the length and character types (uppercase, lowercase, numbers, symbols) to generate passwords that meet any website's requirements." },
      { question: "How are the passwords generated?", answer: "Passwords are generated using the Web Crypto API's crypto.getRandomValues() function, which provides cryptographically secure pseudo-random numbers. This is the same level of randomness that browsers use for HTTPS/TLS encryption, making the generated passwords suitable for security-sensitive applications." },
      { question: "How long should my password be?", answer: "We recommend at least 12 characters for strong security. A 12-character password with mixed character types has over 200 trillion possible combinations. For high-security accounts (banking, email), consider 16-20 characters. Longer passwords are exponentially harder to crack through brute force." },
      { question: "Are my generated passwords stored or sent anywhere?", answer: "No. Passwords are generated entirely in your browser and are never transmitted to any server. There is no database, no logging, and no tracking. Once you navigate away from the page or close the tab, the password is gone forever." },
      { question: "Does it work offline?", answer: "Yes. The password generator uses only browser-native APIs (Web Crypto API) to generate passwords. Once the page has loaded, no internet connection is needed to generate, copy, or regenerate passwords." },
      { question: "What makes a password strong?", answer: "A strong password is long (12+ characters), uses a mix of character types (uppercase, lowercase, numbers, symbols), avoids dictionary words and common patterns, and is unique to each account. The built-in strength meter evaluates your password against these criteria in real time." },
    ],
    features: ["Customizable Length (4-64 chars)", "Uppercase Letters", "Lowercase Letters", "Numbers", "Special Characters", "Real-time Strength Meter", "One-click Copy", "Cryptographically Secure (Web Crypto API)"],
    examples: { input: "Length: 16, Uppercase: Yes, Numbers: Yes, Symbols: Yes", output: { "Generated Password": "xK9#mP2$vL5@nQ8w", Strength: "Very Strong" } },
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    shortName: "BMI Calc",
    description: "Calculate your Body Mass Index and see your health category.",
    longDescription: "Calculate your Body Mass Index (BMI) quickly and accurately. Enter your height and weight to find out if you're underweight, normal weight, overweight, or obese. Includes BMI chart and health category explanations for better understanding of your results.",
    category: "math",
    icon: Heart,
    keywords: ["bmi calculator", "body mass index", "bmi checker", "healthy weight", "bmi chart", "weight calculator"],
    metaTitle: "Free BMI Calculator – Calculate Body Mass Index Online",
    metaDescription: "Calculate your BMI instantly with metric or imperial units. Free online BMI calculator with health categories and visual chart. No sign-up required.",
    primaryKeyword: "BMI calculator",
    howToUse: ["Select your preferred unit system (Metric or Imperial).", "Enter your weight and height in the fields provided.", "Click 'Calculate BMI' to see your results.", "Review the BMI scale and health category for context."],    faq: [
      { question: "What is a BMI Calculator?", answer: "A BMI (Body Mass Index) calculator is a free online tool that estimates whether your weight is in a healthy range relative to your height. It uses the standard BMI formula and categorizes your result as underweight, normal weight, overweight, or obese based on WHO guidelines." },
      { question: "How is BMI calculated?", answer: "BMI is calculated by dividing your weight in kilograms by the square of your height in meters (BMI = kg / m\u00b2). For imperial units, the formula is: BMI = (weight in pounds \u00d7 703) / (height in inches)\u00b2. The calculator handles both unit systems automatically." },
      { question: "What is a healthy BMI range?", answer: "According to the World Health Organization, a BMI between 18.5 and 24.9 is considered normal weight. Below 18.5 is underweight, 25.0-29.9 is overweight, and 30.0 or above is classified as obese. These ranges apply to adults aged 20 and older." },
      { question: "Is BMI accurate for athletes and bodybuilders?", answer: "BMI has limitations \u2014 it does not distinguish between muscle and fat mass. Athletes and bodybuilders may have a high BMI due to greater muscle mass, which weighs more than fat. For these individuals, BMI may overestimate body fat. Other measurements like body fat percentage may be more useful." },
      { question: "Is my health data stored or sent to a server?", answer: "No. All calculations happen entirely in your browser. Your height, weight, and BMI results are never transmitted to any server. No data is stored, logged, or shared with any third party." },
      { question: "Does the BMI calculator work offline?", answer: "Yes. Once the page has loaded, the calculator works completely offline. All the BMI computation is done using simple JavaScript math in your browser with no internet connection required." },
    ],
    features: ["Metric & Imperial Units", "BMI Calculation", "Health Category Classification", "Visual BMI Scale", "Underweight/Normal/Overweight/Obese Labels"],
    examples: { input: "Weight: 70 kg, Height: 175 cm", output: { BMI: "22.9", Category: "Normal weight", "Healthy Range": "18.5 - 24.9" } },
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    shortName: "Percentage",
    description: "Calculate percentages, percentage change, and percentage difference.",
    longDescription: "Calculate any percentage easily with multiple calculation modes. Find what percent of a number is, calculate percentage increase or decrease, and find the percentage difference between two numbers. Essential for students, business owners, and financial calculations.",
    category: "math",
    icon: Percent,
    keywords: ["percentage calculator", "percent calculator", "percentage increase", "percentage decrease", "percent of", "calculate percentage"],
    metaTitle: "Free Percentage Calculator – Calculate Percentages Instantly",
    metaDescription: "Calculate percentages, increase, decrease and change instantly. Free online percentage calculator for students, business and finance. Works in browser.",
    primaryKeyword: "percentage calculator",
    howToUse: ["Choose a calculation mode: '% of Number', '% of What?', or '% Change'.", "Enter your numbers in the input fields.", "Click 'Calculate' to see the result instantly.", "Use the common examples below for quick reference."],    faq: [
      { question: "What is a Percentage Calculator?", answer: "A percentage calculator is a free online tool that lets you quickly compute percentages, percentage increases and decreases, and percentage differences between two numbers. It offers multiple calculation modes so you can solve any percentage problem without memorizing formulas." },
      { question: "How do I calculate a percentage increase or decrease?", answer: "Use the '% Change' tab. Enter the original value in the 'From' field and the new value in the 'To' field. The calculator will show you the percentage change \u2014 positive for an increase and negative for a decrease. The formula used is: ((New - Original) / Original) \u00d7 100." },
      { question: "Can I calculate what percentage one number is of another?", answer: "Yes. Use the '% of What?' tab. Enter the smaller number (the part) in the first field and the larger number (the whole) in the second field. For example, entering 50 and 200 gives you 25%, meaning 50 is 25% of 200." },
      { question: "Does the calculator handle decimal percentages?", answer: "Yes, you can enter decimal percentages like 0.5% or 12.75%. The calculator handles all decimal values with full precision, so you get accurate results even for very small or very specific percentages." },
      { question: "Is my data stored anywhere?", answer: "No. All percentage calculations are performed entirely in your browser using JavaScript. No numbers are sent to any server, and no calculation history is stored." },
      { question: "Does it work offline?", answer: "Yes. Once the page has loaded, the percentage calculator works completely offline. All computations are done locally in your browser with no internet connection needed." },
    ],
    features: ["Percentage of a Number", "What Percent is X of Y", "Percentage Increase/Decrease", "Percentage Difference", "Instant Results"],
    examples: { input: "What is 15% of 200?", output: { Result: "30", Calculation: "200 × 0.15 = 30" } },
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    shortName: "Age Calc",
    description: "Calculate your exact age in years, months, and days.",
    longDescription: "Calculate your exact age in years, months, weeks, days, hours, minutes, and seconds. Simply enter your date of birth and get a detailed breakdown of your age. Also calculates days until your next birthday.",
    category: "math",
    icon: Calendar,
    keywords: ["age calculator", "calculate age", "how old am I", "age in days", "birthday calculator", "date of birth calculator"],
    metaTitle: "Free Age Calculator – Exact Age in Years, Months & Days",
    metaDescription: "Calculate your exact age in years, months, days, hours and seconds. Free online age calculator with next birthday countdown and zodiac sign.",
    primaryKeyword: "age calculator",
    howToUse: ["Enter your date of birth in the first date field.", "Optionally change the 'Age at Date' to calculate age at a specific point.", "Click 'Calculate Age' to see a detailed age breakdown.", "View your zodiac sign, day of birth, and next birthday countdown."],    faq: [
      { question: "What is an Age Calculator?", answer: "An age calculator is a free online tool that computes your exact age in years, months, weeks, days, hours, minutes, and seconds from your date of birth. It also shows your zodiac sign, day of the week you were born, and a countdown to your next birthday." },
      { question: "How does the age calculator handle leap years?", answer: "The calculator uses JavaScript's built-in Date object which correctly accounts for leap years (years divisible by 4, except century years not divisible by 400). This means your age in days is always accurate, even if you were born on or near February 29." },
      { question: "Can I calculate age between any two dates?", answer: "Yes. By default, it calculates from your birth date to today, but you can change the 'Age at Date' field to any date \u2014 past or future. This lets you calculate age differences between any two dates, not just birth dates." },
      { question: "How is the zodiac sign determined?", answer: "The zodiac sign is calculated based on your birth month and day using standard Western astrological date ranges. For example, March 21 to April 19 is Aries. The calculator handles all 12 zodiac signs and their exact date boundaries." },
      { question: "Is my date of birth stored or sent to a server?", answer: "No. All calculations happen entirely in your browser. Your date of birth and calculated age are never transmitted to any server or stored anywhere. Privacy is fully maintained." },
      { question: "Does the age calculator work offline?", answer: "Yes. Once the page has loaded, the age calculator works completely offline. All date calculations are performed locally in your browser using JavaScript with no internet connection required." },
    ],
    features: ["Exact Age in Years/Months/Days", "Age in Weeks, Hours, Minutes", "Next Birthday Countdown", "Zodiac Sign Detection", "Day of Birth", "Custom 'Age at Date' Support"],
    examples: { input: "Date of Birth: January 15, 2000", output: { Age: "26 years, 6 months", "Total Days": "9,684", Zodiac: "Capricorn" } },
  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    shortName: "Loan Calc",
    description: "Calculate monthly payments, total interest, and amortization.",
    longDescription: "Calculate your monthly loan payments, total interest paid, and view a complete amortization schedule. Works for mortgages, car loans, personal loans, and any fixed-rate loan. Adjust interest rate, loan term, and principal to find the perfect loan for your budget.",
    category: "math",
    icon: Banknote,
    keywords: ["loan calculator", "mortgage calculator", "emi calculator", "monthly payment", "interest calculator", "amortization schedule"],
    metaTitle: "Free Loan Calculator – Monthly Payment & Amortization",
    metaDescription: "Calculate monthly loan payments, total interest and view amortization schedule. Free mortgage and EMI calculator. Works for any fixed-rate loan.",
    primaryKeyword: "loan calculator",
    howToUse: ["Enter the total loan amount in dollars.", "Enter the annual interest rate as a percentage (e.g., 6.5 for 6.5%).", "Enter the loan term in years.", "Click 'Calculate Payment' to see monthly payment, total cost, and full amortization schedule."],    faq: [
      { question: "What is a Loan Calculator?", answer: "A loan calculator is a free online tool that computes your monthly payment, total interest paid, and total cost for any fixed-rate loan. It also generates a complete amortization schedule showing how each payment is split between principal and interest over the life of the loan." },
      { question: "How is the monthly payment calculated?", answer: "The monthly payment is calculated using the standard amortization formula: M = P \u00d7 [r(1+r)^n] / [(1+r)^n - 1], where P is the loan principal, r is the monthly interest rate (annual rate / 12), and n is the total number of payments (years \u00d7 12)." },
      { question: "What types of loans does this calculator support?", answer: "This calculator works for any fixed-rate loan including mortgages, car loans, personal loans, student loans, and business loans. It does not support adjustable-rate mortgages (ARMs) or loans with variable interest rates." },
      { question: "What is an amortization schedule?", answer: "An amortization schedule is a complete table showing every monthly payment over the life of the loan. For each payment, it breaks down how much goes toward interest and how much reduces the principal balance. It also shows the remaining balance after each payment." },
      { question: "Is my financial data stored or sent anywhere?", answer: "No. All calculations are performed entirely in your browser. Your loan amount, interest rate, and all results are never transmitted to any server. No financial data is stored or logged." },
      { question: "Does the loan calculator work offline?", answer: "Yes. Once the page has loaded, the loan calculator works completely offline. All amortization calculations are done locally in your browser with no internet connection needed." },
    ],
    features: ["Monthly Payment Calculation", "Total Interest Paid", "Total Cost of Loan", "Full Amortization Schedule", "Supports Any Fixed-Rate Loan", "Mortgage/Car/Personal Loan Ready"],
    examples: { input: "Loan: $250,000, Rate: 6.5%, Term: 30 years", output: { "Monthly Payment": "$1,580.17", "Total Interest": "$318,861.22", "Total Cost": "$568,861.22" } },
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    shortName: "Unit Convert",
    description: "Convert between units of length, weight, temperature, and more.",
    longDescription: "Convert between hundreds of units across multiple categories including length, weight, temperature, volume, area, speed, time, and data. Fast, accurate, and easy to use unit conversion tool for students, professionals, and everyday use.",
    category: "math",
    icon: ArrowLeftRight,
    keywords: ["unit converter", "length converter", "weight converter", "temperature converter", "metric converter", "measurement converter"],
    metaTitle: "Free Unit Converter – Length, Weight, Temperature & More",
    metaDescription: "Convert between units of length, weight, temperature, volume, speed and data storage. Free online unit converter. Metric and imperial supported.",
    primaryKeyword: "unit converter",
    howToUse: ["Select a category (Length, Weight, Temperature, Volume, Area, Speed, or Data).", "Choose the unit you're converting from and to using the dropdowns.", "Enter a value in the 'From' field — the 'To' field updates instantly.", "Click the swap button to reverse the conversion direction."],    faq: [
      { question: "What is a Unit Converter?", answer: "A unit converter is a free online tool that converts values between different units of measurement across 7 categories: length, weight, temperature, volume, area, speed, and data storage. It supports both metric and imperial systems and converts between them instantly." },
      { question: "How accurate are the conversions?", answer: "All conversions use precise, internationally recognized conversion factors. For example, 1 inch equals exactly 2.54 centimeters by definition. Temperature conversions use the exact formulas. There is no rounding error beyond standard floating-point precision." },
      { question: "Can I convert between metric and imperial units?", answer: "Absolutely. The converter seamlessly handles conversions between metric (kilometers, kilograms, Celsius) and imperial (miles, pounds, Fahrenheit) systems. You can also convert between less common units like nautical miles, stone, or Kelvin." },
      { question: "What unit categories are available?", answer: "There are 7 categories with multiple units each: Length (mm, cm, m, km, inch, foot, yard, mile, nautical mile), Weight (mg, g, kg, pound, ounce, stone, ton), Temperature (Celsius, Fahrenheit, Kelvin), Volume (ml, liter, gallon, cup, fluid ounce), Area, Speed (m/s, km/h, mph, knots), and Data Storage (bit, byte, KB, MB, GB, TB)." },
      { question: "Is my data stored or sent to a server?", answer: "No. All conversions are calculated entirely in your browser using JavaScript. The values you enter are never transmitted to any server or stored anywhere." },
      { question: "Does the unit converter work offline?", answer: "Yes. Once the page has loaded, the unit converter works completely offline. All conversion factors are embedded in the tool, so no internet connection is needed to perform any conversion." },
    ],
    features: ["7 Unit Categories", "Length/Weight/Temperature/Volume/Area/Speed/Data", "Instant Conversion", "Swap Direction Button", "Metric & Imperial Support", "Precise Mathematical Factors"],
    examples: { input: "100 kilometers → miles", output: { Result: "62.137 miles", Category: "Length" } },
  },
  {
    id: "case-converter",
    name: "Case Converter",
    shortName: "Case Convert",
    description: "Convert text to uppercase, lowercase, title case, and more.",
    longDescription: "Instantly convert your text between different cases including uppercase, lowercase, title case, sentence case, camelCase, PascalCase, snake_case, and kebab-case. Perfect for developers, writers, and anyone who needs to format text quickly.",
    category: "text",
    icon: CaseSensitive,
    keywords: ["case converter", "uppercase converter", "lowercase converter", "title case", "sentence case", "text case changer"],
    metaTitle: "Free Case Converter – Uppercase, Title Case, camelCase & More",
    metaDescription: "Convert text to uppercase, lowercase, title case, camelCase, snake_case and more. Free online case converter. Copy results instantly.",
    primaryKeyword: "case converter",
    howToUse: ["Type or paste your text into the input area.", "Click any conversion button (UPPERCASE, lowercase, Title Case, etc.).", "The converted text appears in the result section below.", "Click 'Copy' to copy the converted text to your clipboard."],    faq: [
      { question: "What is a Case Converter?", answer: "A case converter is a free online tool that transforms text between different letter cases including UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case. It is essential for developers, writers, and anyone who needs to reformat text quickly." },
      { question: "What is the difference between camelCase and PascalCase?", answer: "camelCase starts with a lowercase letter and each subsequent word starts with uppercase (e.g., myVariableName). PascalCase (also called UpperCamelCase) starts every word with an uppercase letter (e.g., MyVariableName). camelCase is standard in JavaScript and Java, while PascalCase is used for class names and React components." },
      { question: "What is snake_case used for?", answer: "snake_case uses underscores between words with all lowercase letters (e.g., my_variable_name). It is the standard naming convention in Python, Ruby, Rust, and for database column names and API parameters in many frameworks." },
      { question: "How does Title Case handle small words?", answer: "Title Case capitalizes the first letter of every word. This is commonly used for headings, titles, and subtitles. The tool converts all words regardless of length, giving you consistent capitalization across your entire text." },
      { question: "Is my text stored or sent to a server?", answer: "No. All case conversion happens entirely in your browser using JavaScript string methods. Your text is never uploaded, stored, or transmitted to any server." },
      { question: "Does the case converter work offline?", answer: "Yes. Once the page has loaded, the case converter works completely offline. All text transformations are done locally in your browser with no internet connection required." },
    ],
    features: ["UPPERCASE", "lowercase", "Title Case", "Sentence case", "camelCase", "PascalCase", "snake_case", "kebab-case", "One-click Copy"],
    examples: { input: "hello world from toolverse", output: { UPPERCASE: "HELLO WORLD FROM TOOLVERSE", "Title Case": "Hello World From Toolverse", camelCase: "helloWorldFromToolverse" } },
  },
  {
    id: "color-picker",
    name: "Color Picker",
    shortName: "Color Pick",
    description: "Pick colors and convert between HEX, RGB, and HSL formats.",
    longDescription: "Pick any color and instantly get its values in HEX, RGB, HSL, and CMYK formats. Use the color wheel or input specific values. Generate color palettes and find complementary colors. Essential tool for designers, developers, and artists.",
    category: "dev",
    icon: Palette,
    keywords: ["color picker", "hex color", "rgb color", "hsl color", "color converter", "color palette generator"],
    metaTitle: "Free Color Picker – HEX, RGB, HSL Converter & Palette Tool",
    metaDescription: "Pick colors and convert between HEX, RGB, HSL formats instantly. Free online color picker with palette generator for designers and developers.",
    primaryKeyword: "color picker",
    howToUse: ["Use the HEX input to enter a color code directly, or adjust the RGB/HSL sliders.", "Click any color value (HEX, RGB, HSL) to copy it to your clipboard.", "View color variations: lighter, darker, and complementary colors.", "Use the generated palette at the bottom for shading inspiration."],    faq: [
      { question: "What is a Color Picker?", answer: "A color picker is a free online tool that lets you select any color and instantly see its values in multiple formats: HEX (#FF5733), RGB (255, 87, 51), and HSL. It also generates color palettes, lighter/darker variations, and complementary colors for design work." },
      { question: "What is the difference between HEX and RGB?", answer: "HEX is a hexadecimal color code prefixed with # (e.g., #FF5733) and is the most common format in CSS and web design. RGB represents a color as three numbers from 0-255 representing the intensity of red, green, and blue light (e.g., rgb(255, 87, 51)). They represent the exact same color \u2014 just in different notations." },
      { question: "What is HSL and when should I use it?", answer: "HSL stands for Hue (0-360\u00b0 on the color wheel), Saturation (0-100% color intensity), and Lightness (0-100% brightness). HSL is more intuitive than HEX/RGB when you want to adjust a color \u2014 for example, making it lighter or less saturated \u2014 because each property maps to a visual characteristic." },
      { question: "How are complementary colors calculated?", answer: "A complementary color is found by shifting the hue by 180\u00b0 on the color wheel. This creates the highest possible contrast between two colors. The tool automatically shows complementary, analogous, and triadic color harmonies in the Color Variations section." },
      { question: "Is any data stored or sent to a server?", answer: "No. All color conversion and palette generation happens entirely in your browser using JavaScript. No color selections, preferences, or data are transmitted to any server." },
      { question: "Does the color picker work offline?", answer: "Yes. Once the page has loaded, the color picker works completely offline. All color conversions between HEX, RGB, and HSL are computed locally in your browser." },
    ],
    features: ["Color Wheel Picker", "HEX/RGB/HSL Formats", "Color Palette Generator", "Lighter/Darker Variations", "Complementary Colors", "One-click Copy Any Value"],
    examples: { input: "#FF5733", output: { HEX: "#FF5733", RGB: "rgb(255, 87, 51)", HSL: "hsl(11, 100%, 60%)" } },
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    shortName: "JSON Format",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    longDescription: "Format, validate, and beautify your JSON data instantly. Paste messy JSON and get perfectly formatted, indented output with syntax highlighting. Includes error detection, JSON minification, and tree view. Essential tool for developers working with APIs and data.",
    category: "dev",
    icon: Braces,
    keywords: ["json formatter", "json beautifier", "json validator", "json viewer", "format json", "pretty print json"],
    metaTitle: "Free JSON Formatter & Validator – Beautify JSON Online",
    metaDescription: "Format, validate and beautify JSON instantly with syntax highlighting. Free online JSON formatter with tree view and minifier. 100% private.",
    primaryKeyword: "JSON formatter",
    howToUse: ["Paste your JSON data into the input text area, or click 'Upload .json' to load a file.", "Click 'Format / Beautify' to pretty-print the JSON with proper indentation.", "Click 'Minify' to compress JSON to a single line.", "Click 'Validate' to check if your JSON is valid without reformatting."],    faq: [
      { question: "What is a JSON Formatter?", answer: "A JSON formatter (also called a JSON beautifier) is a free online developer tool that takes messy or minified JSON data and formats it with proper indentation, line breaks, and syntax highlighting. It also validates JSON syntax and can minify formatted JSON back to a compact single-line form." },
      { question: "Why is my JSON showing an error?", answer: "Common JSON errors include: trailing commas after the last item in an array or object (not allowed in standard JSON), single quotes instead of double quotes around strings and keys, unquoted object keys, missing commas between elements, and comments (JSON does not support comments). The error message shows the exact position of the problem." },
      { question: "Can I upload a .json file instead of pasting?", answer: "Yes. Click the 'Upload .json' button to load a JSON file directly from your device. The file is read entirely in your browser using the FileReader API \u2014 it is never uploaded to any server." },
      { question: "What is JSON minification and why use it?", answer: "JSON minification removes all unnecessary whitespace (spaces, tabs, line breaks) to produce the most compact representation. This reduces file size for API payloads, reduces network transfer time, and is standard practice for production configurations and data exchange." },
      { question: "Is my JSON data sent to a server?", answer: "No. All JSON formatting, validation, and minification happens entirely in your browser using JavaScript's built-in JSON.parse() and JSON.stringify() methods. Your data is never transmitted to any external server." },
      { question: "Does the JSON formatter work offline?", answer: "Yes. Once the page has loaded, the JSON formatter works completely offline. All parsing and formatting is done locally in your browser with no internet connection required." },
    ],
    features: ["Format & Beautify", "Minify JSON", "Validate Syntax", "Syntax Highlighting", "Error Detection with Line Numbers", "Tree View", "Upload .json Files"],
    examples: { input: '{"name":"John","age":30}', output: { Status: "Valid JSON", Formatted: "3 lines, properly indented", Keys: "2" } },
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    shortName: "Image Compress",
    description: "Compress and resize images right in your browser. Supports JPEG, PNG, WebP.",
    longDescription: "Compress and resize images directly in your browser without uploading to any server. Adjust quality, change dimensions, and convert between JPEG, PNG, and WebP formats. See instant file size comparison before downloading. Perfect for optimizing images for web, email, and social media.",
    category: "image",
    icon: ImageDown,
    keywords: ["image compressor", "compress image", "resize image", "reduce image size", "image optimizer", "jpeg compressor", "png compressor", "webp converter"],
    metaTitle: "Free Image Compressor – Compress JPEG, PNG, WebP Online",
    metaDescription: "Compress and resize images online for free. Reduce file size up to 90%. Convert between JPEG, PNG and WebP. 100% private, all processing in your browser.",
    primaryKeyword: "image compressor",
    howToUse: ["Click or drag and drop an image file into the upload area.", "Adjust the quality slider and optionally set max width/height.", "Choose your preferred output format (JPEG, PNG, or WebP).", "Click 'Download Compressed Image' to save the optimized file."],    faq: [
      { question: "What is an Image Compressor?", answer: "An image compressor is a free online tool that reduces the file size of images directly in your browser. It supports JPEG, PNG, and WebP formats and lets you adjust quality settings and dimensions. You can see the before/after file size comparison before downloading." },
      { question: "Does compression reduce image quality?", answer: "It depends on the format and quality setting. Lossy formats (JPEG, WebP) reduce file size by discarding some image data \u2014 lower quality settings mean more data is discarded. PNG uses lossless compression, so quality is fully preserved. You control the quality level with the slider to find the right balance between file size and visual quality." },
      { question: "What image formats can I upload and export?", answer: "You can upload JPEG, PNG, WebP, GIF, and BMP images. For output, you can choose between JPEG (best for photos), PNG (best for graphics with text/transparency), and WebP (modern format with excellent compression for both photos and graphics)." },
      { question: "Is my image uploaded to a server?", answer: "No. All compression is performed entirely in your browser using the HTML5 Canvas API. Your images never leave your device \u2014 there are no server uploads, no cloud processing, and no data transmission of any kind." },
      { question: "Can I resize images at the same time?", answer: "Yes. You can set a maximum width and/or height, and the compressor will resize the image proportionally while compressing it. This is useful for preparing images for web pages, social media, or email where specific dimensions are needed." },
      { question: "Does the image compressor work offline?", answer: "Yes. Once the page has loaded, the image compressor works completely offline. All processing uses browser-native Canvas APIs with no internet connection needed to compress images." },
    ],
    features: ["JPEG/PNG/WebP Support", "Quality Slider (1-100%)", "Custom Width/Height Resize", "Before/After File Size Comparison", "Bulk Processing Ready", "100% Browser-side Processing"],
    examples: { input: "photo.png (2.4 MB)", output: { "Compressed Size": "480 KB", Reduction: "80%", Format: "WebP" } },
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    shortName: "QR Code",
    description: "Generate customizable QR codes from text or URLs. Download as PNG.",
    longDescription: "Generate QR codes instantly from any text, URL, email address, phone number, or WiFi credentials. Customize size, colors, and download as a high-quality PNG image. Perfect for business cards, marketing materials, and sharing links.",
    category: "dev",
    icon: QrCode,
    keywords: ["qr code generator", "create qr code", "qr code maker", "free qr code", "qr code online", "generate qr", "custom qr code"],
    metaTitle: "Free QR Code Generator – Create Custom QR Codes Online",
    metaDescription: "Generate free QR codes from text or URLs. Customize colors and size. Download as PNG. No sign-up required, 100% free.",
    primaryKeyword: "QR code generator",
    howToUse: ["Enter your text or URL in the input field.", "Customize the QR code size using the slider.", "Optionally change the foreground and background colors.", "Click 'Download PNG' or 'Copy to Clipboard' to save your QR code."],    faq: [
      { question: "What is a QR Code Generator?", answer: "A QR code generator is a free online tool that creates scannable QR codes from any text or URL. You can customize the size, colors, and download the result as a high-quality PNG image. QR codes are used for sharing links, business cards, WiFi passwords, and more." },
      { question: "What types of content can I encode?", answer: "You can encode any text content \u2014 website URLs, email addresses (mailto:), phone numbers (tel:), WiFi credentials, vCard contact information, or plain text. The QR code simply stores whatever text you enter; how it is interpreted depends on the scanner app." },
      { question: "Is there a limit to how much text a QR code can hold?", answer: "Yes. A standard QR code can hold up to approximately 4,296 alphanumeric characters or 7,089 numeric digits. Longer content produces denser QR codes with smaller modules (dots), which may be harder to scan at small sizes. For best results, keep URLs under 300 characters." },
      { question: "Can I customize the QR code colors?", answer: "Yes. You can change both the foreground (dark modules) and background colors. However, for reliable scanning, maintain high contrast between foreground and background (e.g., dark foreground on light background). Very low contrast combinations may not scan properly." },
      { question: "Is my data stored or sent to a server?", answer: "No. The QR code is generated entirely in your browser using JavaScript. The text or URL you enter is never sent to any server. No data is stored, tracked, or logged." },
      { question: "Does the QR code generator work offline?", answer: "Yes. Once the page has loaded, the QR code generator works completely offline. The QR code rendering library is loaded with the page, so no internet connection is needed to generate or download QR codes." },
    ],
    features: ["Text/URL Encoding", "Custom Size (100-1000px)", "Custom Foreground Color", "Custom Background Color", "Download as PNG", "Copy to Clipboard"],
    examples: { input: "https://toolhub-utilities.vercel.app", output: { Size: "300×300px", Format: "PNG", Scannable: "Yes" } },
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    shortName: "Base64",
    description: "Encode text or files to Base64, or decode Base64 back to text or files.",
    longDescription: "Encode text to Base64 or decode Base64 strings back to text. Also supports encoding files to Base64 data URIs and decoding Base64 back to downloadable files. Essential tool for developers working with data URIs, API payloads, and binary data in text format.",
    category: "dev",
    icon: Binary,
    keywords: ["base64 encoder", "base64 decoder", "encode base64", "decode base64", "base64 converter", "file to base64", "base64 to file"],
    metaTitle: "Free Base64 Encoder/Decoder – Text & File Conversion",
    metaDescription: "Encode text or files to Base64 and decode Base64 back. Supports Unicode text, file uploads, and data URI conversion. Free online tool.",
    primaryKeyword: "base64 encoder",
    howToUse: ["Switch to the 'Encode' tab to convert text or files to Base64.", "Switch to the 'Decode' tab to convert Base64 back to text or a file.", "Paste your input or upload a file, then click the action button.", "Copy the result or download the decoded file."],    faq: [
      { question: "What is Base64 encoding?", answer: "Base64 is a binary-to-text encoding scheme that represents binary data using a set of 64 ASCII characters (A-Z, a-z, 0-9, +, /). It is commonly used to embed images in HTML/CSS, send binary data in JSON payloads, encode email attachments, and represent binary data in text-based formats like XML or configuration files." },
      { question: "How does Base64 encoding work?", answer: "The encoder reads your input (text or file), converts it to a sequence of bytes (using UTF-8 for text), then groups those bytes into chunks of 3. Each 3-byte chunk (24 bits) is split into four 6-bit numbers, each mapped to one of the 64 Base64 characters. If the final chunk has fewer than 3 bytes, padding characters (=) are added." },
      { question: "Does it support Unicode characters and emojis?", answer: "Yes. The encoder first converts your text to UTF-8 bytes before Base64 encoding. This means it correctly handles all Unicode characters including emojis, Chinese/Japanese/Korean characters, accented letters, and any other non-ASCII text." },
      { question: "Can I encode files to Base64?", answer: "Yes. Click 'Upload File' on the Encode tab to convert any file to a Base64 data URI string. This is useful for embedding small images directly in HTML or CSS, or preparing binary data for JSON API payloads." },
      { question: "Is my data stored or sent to a server?", answer: "No. All encoding and decoding happens entirely in your browser using the btoa() and atob() JavaScript APIs (or the FileReader API for files). Your data is never uploaded or transmitted to any server." },
      { question: "Does the Base64 tool work offline?", answer: "Yes. Once the page has loaded, the Base64 encoder/decoder works completely offline. All encoding and decoding uses browser-native APIs with no internet connection required." },
    ],
    features: ["Text to Base64 Encoding", "Base64 to Text Decoding", "File to Base64 Data URI", "Base64 to File Download", "Unicode/Emoji Support", "UTF-8 Encoding"],
    examples: { input: "Hello World", output: { Encoded: "SGVsbG8gV29ybGQ=", Decoded: "Hello World" } },
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    shortName: "URL Encode",
    description: "Encode and decode URLs with automatic URL component breakdown.",
    longDescription: "Encode special characters in URLs for safe transmission, or decode percent-encoded URLs back to readable text. Includes automatic URL breakdown showing scheme, host, path, query parameters, and fragment. Essential for web developers working with APIs and web addresses.",
    category: "dev",
    icon: Link,
    keywords: ["url encoder", "url decoder", "encode url", "decode url", "percent encoding", "url encode online", "urlencode"],
    metaTitle: "Free URL Encoder/Decoder – Percent Encoding Tool",
    metaDescription: "Encode and decode URLs instantly. See automatic URL breakdown with scheme, host, path and query params. Free online tool for developers.",
    primaryKeyword: "URL encoder",
    howToUse: ["Switch to 'Encode' tab to encode special characters in a URL.", "Switch to 'Decode' tab to decode a percent-encoded URL.", "Paste your URL and click the action button.", "View the URL breakdown panel to see parsed components."],    faq: [
      { question: "What is a URL Encoder?", answer: "A URL encoder is a free online tool that converts special characters in URLs to percent-encoded format (e.g., space becomes %20) for safe transmission. It also decodes percent-encoded URLs back to readable text. It includes an automatic URL breakdown showing scheme, host, path, and query parameters." },
      { question: "What is percent encoding?", answer: "Percent encoding (also called URL encoding) replaces unsafe ASCII characters with a '%' symbol followed by two hexadecimal digits representing the character's byte value. For example, a space becomes %20, '&' becomes %26, and '?' becomes %3F. This ensures URLs can be safely transmitted over the internet without ambiguity." },
      { question: "When should I URL-encode a string?", answer: "URL-encode whenever you need to include special characters in a URL's query parameter or path segment. This includes spaces, ampersands, equals signs, question marks, hash symbols, and non-ASCII characters. Without encoding, these characters can break URL parsing or be misinterpreted by servers." },
      { question: "What is the difference between encodeURI and encodeURIComponent?", answer: "encodeURI() is designed for full URLs and leaves URL structure characters intact (:, /, ?, &, =, #). encodeURIComponent() encodes ALL special characters including these, making it the correct choice for individual query parameter values. The tool lets you choose which method to use." },
      { question: "Is my URL data stored or sent to a server?", answer: "No. All encoding and decoding happens entirely in your browser using JavaScript's built-in encodeURI(), encodeURIComponent(), decodeURI(), and decodeURIComponent() functions. Your URLs are never transmitted to any server." },
      { question: "Does the URL encoder work offline?", answer: "Yes. Once the page has loaded, the URL encoder/decoder works completely offline. All encoding and decoding uses browser-native JavaScript functions with no internet connection needed." },
    ],
    features: ["URL Encode Special Characters", "URL Decode Percent-Encoding", "Automatic URL Component Breakdown", "encodeURI vs encodeURIComponent", "Parse Scheme/Host/Path/Query"],
    examples: { input: "hello world & foo=bar", output: { Encoded: "hello%20world%20%26%20foo%3Dbar", Decoded: "hello world & foo=bar" } },
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    shortName: "Lorem Ipsum",
    description: "Generate placeholder text in paragraphs, sentences, or words.",
    longDescription: "Generate lorem ipsum placeholder text for your designs, mockups, and prototypes. Choose the number of paragraphs, sentences, or words. Option to start with the classic 'Lorem ipsum dolor sit amet' opening. Perfect for designers, developers, and content creators.",
    category: "text",
    icon: FileText,
    keywords: ["lorem ipsum generator", "placeholder text", "dummy text", "filler text", "lorem ipsum", "sample text generator", "mockup text"],
    metaTitle: "Free Lorem Ipsum Generator – Placeholder Text Tool",
    metaDescription: "Generate lorem ipsum placeholder text by paragraphs, sentences or words. Customizable count and options. Copy instantly. Free online tool.",
    primaryKeyword: "lorem ipsum generator",
    howToUse: ["Select the type: Paragraphs, Sentences, or Words.", "Set the count using the number input.", "Toggle 'Start with Lorem ipsum dolor sit amet' if desired.", "Click 'Copy All' to copy the generated text to your clipboard."],    faq: [
      { question: "What is a Lorem Ipsum Generator?", answer: "A lorem ipsum generator is a free online tool that creates placeholder (dummy) text for designs, mockups, and prototypes. It generates realistic-looking text that mimics natural language, allowing designers and developers to visualize how real content will look without needing actual copy." },
      { question: "What is lorem ipsum text?", answer: "Lorem ipsum is placeholder text derived from a 1st-century BC Latin text by the Roman philosopher Cicero (De Finibus Bonorum et Malorum). It has been the printing and typesetting industry's standard dummy text since the 1500s. While it resembles Latin, the text has been scrambled over centuries and is not grammatically correct." },
      { question: "Can I customize how much text is generated?", answer: "Yes. You can generate text in three modes: by Paragraphs (1-20), by Sentences (1-50), or by Words (1-500). The text regenerates instantly as you adjust the count, and you can toggle the classic 'Lorem ipsum dolor sit amet...' opening sentence." },
      { question: "Why use lorem ipsum instead of real text?", answer: "Lorem ipsum allows viewers to focus on the visual design (layout, typography, spacing) rather than reading the content. This is important during the design phase when actual copy may not be available yet. It provides a realistic impression of text density and flow without distracting the reviewer." },
      { question: "Is any data stored or sent to a server?", answer: "No. The lorem ipsum text is generated entirely in your browser using a built-in word list and generation algorithm. No data is transmitted to any server." },
      { question: "Does the lorem ipsum generator work offline?", answer: "Yes. Once the page has loaded, the generator works completely offline. The Latin word list and generation algorithm are embedded in the page, so no internet connection is needed to generate placeholder text." },
    ],
    features: ["Paragraphs/Sentences/Words Modes", "Custom Count (1-500)", "Classic Opening Option", "One-click Copy All", "Instant Regeneration"],
    examples: { input: "Type: Paragraphs, Count: 2", output: { Words: "~80", Paragraphs: "2", Copied: "Yes" } },
  },
  {
    id: "markdown-previewer",
    name: "Markdown Previewer",
    shortName: "Markdown",
    description: "Write Markdown and see a live HTML preview with split-view editor.",
    longDescription: "Write Markdown in a split-view editor and see a live HTML preview in real time. Supports full GitHub Flavored Markdown including tables, code blocks with syntax highlighting, task lists, and more. Copy the rendered HTML output. Perfect for writing README files, documentation, and blog posts.",
    category: "text",
    icon: AlignLeft,
    keywords: ["markdown previewer", "markdown editor", "markdown to html", "markdown viewer", "online markdown", "gfm previewer", "markdown live preview"],
    metaTitle: "Free Markdown Previewer – Live Editor with HTML Export",
    metaDescription: "Write Markdown and see live HTML preview instantly. Supports GFM, tables, code blocks. Copy HTML output. Free online tool, no sign-up.",
    primaryKeyword: "markdown previewer",
    howToUse: ["Type or paste Markdown in the left editor panel.", "See the rendered HTML preview on the right in real time.", "Switch between Split, Preview, and HTML Source views.", "Click 'Copy HTML' to copy the rendered HTML to your clipboard."],    faq: [
      { question: "What is a Markdown Previewer?", answer: "A Markdown previewer is a free online tool that lets you write Markdown text in a split-view editor and see a live HTML preview in real time. It supports GitHub Flavored Markdown (GFM) including tables, code blocks, task lists, and more. You can also copy the rendered HTML output for use in blogs, CMS platforms, or emails." },
      { question: "What Markdown features are supported?", answer: "The previewer supports the full GitHub Flavored Markdown specification including: headings (h1-h6), bold and italic text, links and images, ordered and unordered lists, code blocks (fenced and inline), tables, task lists (checkboxes), blockquotes, horizontal rules, and strikethrough text." },
      { question: "Can I export the rendered HTML?", answer: "Yes. Click the 'Copy HTML' button to copy the fully rendered HTML to your clipboard. You can then paste it directly into a CMS (like WordPress), an HTML file, an email client, or any other application that accepts HTML content." },
      { question: "Does it support syntax highlighting for code blocks?", answer: "Code blocks are rendered with proper formatting, monospace font, and styled backgrounds for clear readability. The tool provides solid code block formatting, and you can copy the output HTML to use with any external syntax highlighting library in your project." },
      { question: "Is my text stored or sent to a server?", answer: "No. All Markdown parsing and HTML rendering happens entirely in your browser. Your text is never uploaded, stored, or transmitted to any server. The preview updates in real time using client-side JavaScript." },
      { question: "Does the Markdown previewer work offline?", answer: "Yes. Once the page has loaded, the Markdown previewer works completely offline. The Markdown parsing library and rendering engine are loaded with the page, so no internet connection is needed to write or preview Markdown." },
    ],
    features: ["Live Split-View Editor", "GitHub Flavored Markdown", "Tables Support", "Code Blocks", "Task Lists", "Copy Rendered HTML", "Split/Preview/HTML Views"],
    examples: { input: "# Hello\n**bold** and *italic*", output: { Rendered: "Heading + bold/italic text", HTML: "<h1>Hello</h1><p><strong>bold</strong>..." } },
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    shortName: "Hash Gen",
    description: "Generate SHA-1, SHA-256, and SHA-512 hashes from any text.",
    longDescription: "Generate cryptographic hashes from any text input using the Web Crypto API. Supports SHA-1, SHA-256, and SHA-512 algorithms. Real-time hashing as you type with one-click copy for each hash. Essential for verifying file integrity, storing passwords securely, and generating checksums.",
    category: "dev",
    icon: Lock,
    keywords: ["hash generator", "sha256", "sha512", "sha1", "hash calculator", "cryptographic hash", "checksum generator", "hash online"],
    metaTitle: "Free Hash Generator – SHA-1, SHA-256, SHA-512 Online",
    metaDescription: "Generate SHA-1, SHA-256 and SHA-512 hashes from any text instantly. Uses Web Crypto API. Free online tool, 100% private.",
    primaryKeyword: "hash generator",
    howToUse: ["Enter or paste your text in the input field.", "View the generated hashes for SHA-1, SHA-256, and SHA-512 below.", "Click the copy icon next to any hash to copy it.", "Hashes update in real time as you type (debounced)."],    faq: [
      { question: "What is a Hash Generator?", answer: "A hash generator is a free online tool that creates cryptographic hash values from any text input. It supports SHA-1, SHA-256, and SHA-512 algorithms using the Web Crypto API. Hashes are used for verifying file integrity, securely storing passwords, generating checksums, and digital signatures." },
      { question: "How are the hashes generated?", answer: "Hashes are generated using the Web Crypto API (crypto.subtle.digest()) built into your browser. This is the same cryptographic library your browser uses for HTTPS/TLS connections. It produces standards-compliant hashes identical to those generated by OpenSSL, Node.js crypto, and other professional tools." },
      { question: "Which hash algorithm should I use?", answer: "SHA-256 is recommended for most modern applications \u2014 it offers an excellent balance of security and performance. SHA-512 provides even stronger security for sensitive applications. SHA-1 is considered cryptographically weak and should only be used for backward compatibility with legacy systems." },
      { question: "Can I hash passwords with this tool?", answer: "You can generate hashes of any text, but for actual password storage in applications, you should use a purpose-built password hashing algorithm like bcrypt, Argon2, or PBKDF2 which add salt and iterations. The SHA hashes from this tool are useful for checksums, file verification, and general-purpose hashing." },
      { question: "Is my text stored or sent to a server?", answer: "No. All hashing happens entirely in your browser using the Web Crypto API. Your input text and generated hashes are never transmitted to any external server. No data is stored or logged." },
      { question: "Does the hash generator work offline?", answer: "Yes. Once the page has loaded, the hash generator works completely offline. The Web Crypto API is a browser-native feature, so no internet connection is needed to generate SHA-1, SHA-256, or SHA-512 hashes." },
    ],
    features: ["SHA-1 Hash", "SHA-256 Hash", "SHA-512 Hash", "Real-time Hashing", "One-click Copy Each Hash", "Web Crypto API (Secure)"],
    examples: { input: "password123", output: { "SHA-256": "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f", "SHA-1": "cbfdac608f1e0c0a88a0c8f6a5dd0b9e705ea6ae3a823f9f5d7e0a3f8a0d0e0" } },
  },
  {
    id: "number-base-converter",
    name: "Number Base Converter",
    shortName: "Base Convert",
    description: "Convert between binary, octal, decimal, and hexadecimal number systems.",
    longDescription: "Convert numbers between binary (base 2), octal (base 8), decimal (base 10), and hexadecimal (base 16) instantly. Supports large numbers using BigInt for arbitrary precision. Perfect for computer science students, programmers, and anyone working with different number systems.",
    category: "math",
    icon: Hash,
    keywords: ["number base converter", "binary converter", "hex converter", "decimal to binary", "hex to decimal", "octal converter", "radix converter"],
    metaTitle: "Free Number Base Converter – Binary, Hex, Octal, Decimal",
    metaDescription: "Convert between binary, octal, decimal and hexadecimal instantly. Supports large numbers with BigInt. Free online tool for programmers and students.",
    primaryKeyword: "number base converter",
    howToUse: ["Select your input base (Binary, Octal, Decimal, or Hexadecimal).", "Enter your number in the input field.", "See the conversion results in all other bases instantly.", "Click any swap button to use a result as your new input."],    faq: [
      { question: "What is a Number Base Converter?", answer: "A number base converter is a free online tool that converts numbers between binary (base 2), octal (base 8), decimal (base 10), and hexadecimal (base 16) number systems. It uses JavaScript BigInt for arbitrary-precision arithmetic, so it handles very large numbers without any loss of precision." },
      { question: "What is binary and why is it important?", answer: "Binary (base 2) is the fundamental number system of computers, using only two digits: 0 and 1. All digital data \u2014 text, images, video, programs \u2014 is ultimately represented as binary. Understanding binary is essential for computer science, programming, and digital electronics." },
      { question: "What is hexadecimal used for?", answer: "Hexadecimal (base 16, using digits 0-9 and letters A-F) is widely used in programming because it represents binary data more compactly \u2014 each hex digit maps to exactly 4 binary bits. Common uses include memory addresses, color codes (#FF5733), Unicode code points, and debugging binary data." },
      { question: "Does it support very large numbers?", answer: "Yes. The converter uses JavaScript's BigInt for arbitrary-precision arithmetic, meaning it can convert numbers of any size without rounding or precision loss. Regular JavaScript numbers lose precision above 2^53, but BigInt handles them correctly." },
      { question: "Is my data stored or sent to a server?", answer: "No. All number base conversions are calculated entirely in your browser using JavaScript BigInt. No numbers are transmitted to any server, and no conversion history is stored." },
      { question: "Does the number base converter work offline?", answer: "Yes. Once the page has loaded, the number base converter works completely offline. All conversion math is done locally in your browser with no internet connection required." },
    ],
    features: ["Binary (Base 2)", "Octal (Base 8)", "Decimal (Base 10)", "Hexadecimal (Base 16)", "BigInt Precision", "Instant All-base Conversion"],
    examples: { input: "255 (Decimal)", output: { Binary: "11111111", Octal: "377", Hexadecimal: "FF" } },
  },
  {
    id: "text-diff-checker",
    name: "Text Diff Checker",
    shortName: "Text Diff",
    description: "Compare two texts and highlight added, removed, and unchanged lines.",
    longDescription: "Compare two pieces of text side by side and instantly see the differences. Added lines are highlighted in green, removed lines in red, and unchanged lines in gray. Shows statistics for lines added, removed, and unchanged. Perfect for comparing code revisions, document versions, and text changes.",
    category: "dev",
    icon: Diff,
    keywords: ["text diff", "compare text", "text difference", "diff checker", "text comparison", "compare two texts", "find differences"],
    metaTitle: "Free Text Diff Checker – Compare Two Texts Online",
    metaDescription: "Compare two texts and see differences highlighted instantly. Shows added, removed and unchanged lines with statistics. Free online diff tool.",
    primaryKeyword: "text diff checker",
    howToUse: ["Paste your original text in the left textarea.", "Paste the modified text in the right textarea.", "Click 'Compare' to see the differences highlighted.", "Review the stats showing lines added, removed, and unchanged."],    faq: [
      { question: "What is a Text Diff Checker?", answer: "A text diff checker is a free online tool that compares two pieces of text side by side and highlights the differences. Added lines appear in green, removed lines in red, and unchanged lines remain neutral. It shows statistics for lines added, removed, and unchanged \u2014 perfect for comparing code revisions, document versions, and text changes." },
      { question: "How does the comparison algorithm work?", answer: "The tool performs a line-by-line comparison between the two texts. It identifies which lines exist only in the original text (removed), which exist only in the modified text (added), and which are identical (unchanged). This gives you a clear visual picture of exactly what changed between two versions." },
      { question: "Is the comparison case-sensitive?", answer: "Yes, the diff comparison is case-sensitive by default. 'Hello' and 'hello' are treated as different lines. This is the correct behavior for source code comparison where casing matters (e.g., variable names in JavaScript, class names in Python)." },
      { question: "Can I compare code files?", answer: "Absolutely. The diff checker works with any plain text, including source code (JavaScript, Python, HTML, CSS, etc.), configuration files (JSON, YAML, .env), log files, and any other text-based format. Simply paste the content from both versions into the left and right textareas." },
      { question: "Is my text stored or sent to a server?", answer: "No. All text comparison happens entirely in your browser using JavaScript. Both texts are processed locally and are never transmitted to any server. No text is stored, cached, or logged." },
      { question: "Does the text diff checker work offline?", answer: "Yes. Once the page has loaded, the diff checker works completely offline. All comparison logic is implemented in client-side JavaScript with no internet connection needed." },
    ],
    features: ["Side-by-side Comparison", "Added Lines (Green)", "Removed Lines (Red)", "Unchanged Lines (Gray)", "Diff Statistics", "Case-sensitive Matching"],
    examples: { input: "Original vs Modified text", output: { Added: "2 lines", Removed: "1 line", Unchanged: "5 lines" } },
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    shortName: "PDF Compress",
    description: "Compress PDF files in your browser. Reduce file size with three compression levels.",
    longDescription: "Compress PDF files directly in your browser without uploading to any server. Choose from three compression levels — Low (structural optimization), Medium (metadata stripping), or High (image re-encoding). See the file size reduction before downloading. Perfect for reducing PDF sizes for email attachments and web uploads.",
    category: "image",
    icon: FileDown,
    keywords: ["pdf compressor", "compress pdf", "reduce pdf size", "pdf optimizer", "pdf compression", "make pdf smaller", "online pdf compressor"],
    metaTitle: "Free PDF Compressor – Reduce PDF File Size Online",
    metaDescription: "Compress PDF files online for free. Three compression levels. No upload needed — all processing in your browser. Reduce PDF size by up to 80%.",
    primaryKeyword: "PDF compressor",
    howToUse: ["Click or drag and drop a PDF file into the upload area.", "Select your compression level (Low, Medium, or High).", "Click 'Compress PDF' and wait for processing.", "Download the compressed PDF and check the size reduction."],    faq: [
      { question: "What is a PDF Compressor?", answer: "A PDF compressor is a free online tool that reduces the file size of PDF documents directly in your browser. It offers three compression levels \u2014 Low, Medium, and High \u2014 and shows you the file size reduction before you download. No upload to any server is required." },
      { question: "How does PDF compression work without a server?", answer: "The compression happens entirely in your browser using client-side JavaScript. Low level removes unused objects and optimizes the PDF structure. Medium level also strips metadata (author, title, creation date, etc.). High level additionally re-encodes embedded images at lower quality for maximum size reduction." },
      { question: "Will compression affect the quality of my PDF?", answer: "Low and Medium compression levels preserve all visual content perfectly. High compression may slightly reduce image quality within the PDF. However, text content, vector graphics, fonts, and page layout are always preserved at every compression level." },
      { question: "Is my PDF uploaded to a server?", answer: "No. All compression is performed entirely in your browser. Your PDF files are never uploaded, transmitted, or stored on any server. The file stays on your device throughout the entire process \u2014 from upload to download." },
      { question: "What PDF compression level should I choose?", answer: "Use Low for minimal size reduction with zero quality loss. Use Medium for a good balance of size reduction and quality preservation \u2014 recommended for most use cases. Use High when file size is the priority and slight image quality reduction is acceptable (e.g., email attachments with size limits)." },
      { question: "Does the PDF compressor work offline?", answer: "Yes. Once the page has loaded, the PDF compressor works completely offline. The PDF processing library is loaded with the page, so no internet connection is needed to compress PDF files." },
    ],
    features: ["3 Compression Levels (Low/Medium/High)", "File Size Comparison", "No Upload Required", "Text & Layout Preserved", "Instant Download", "100% Private Processing"],
    examples: { input: "document.pdf (5.2 MB)", output: { "Compressed Size": "1.8 MB", Reduction: "65%", Level: "Medium" } },
  },
];