import {
  Type,
  Hash,
  Shield,
  Heart,
  Percent,
  Calendar,
  Banknote,
  ArrowLeftRight,
  CaseSensitive,
  Palette,
  Braces,
  ImageDown,
  QrCode,
  Binary,
  Link,
  FileText,
  AlignLeft,
  Lock,
  Diff,
  FileDown,
  TextCursorInput,
} from "lucide-react";
import { type LucideIcon } from "lucide-react";

export interface ToolDef {
  id: string;
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  category: string;
  icon: LucideIcon;
  keywords: string[];
  metaTitle: string;
  metaDescription: string;
  primaryKeyword: string;
  howToUse: string[];
  faq: { question: string; answer: string }[];
}

export const toolCategories = [
  { id: "text", name: "Text Tools", color: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300" },
  { id: "math", name: "Math Calculators", color: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300" },
  { id: "dev", name: "Developer Tools", color: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300" },
  { id: "image", name: "Image Tools", color: "bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300" },
];

export const tools: ToolDef[] = [
  {
    id: "word-counter",
    name: "Word Counter",
    shortName: "Word Count",
    description: "Count words, characters, sentences, and paragraphs instantly.",
    longDescription: "Free online word counter tool. Instantly count words, characters (with and without spaces), sentences, paragraphs, and estimated reading time. Perfect for writers, students, bloggers, and SEO professionals who need to meet specific word count requirements.",
    category: "text",
    icon: Type,
    keywords: ["word counter", "character counter", "word count tool", "online word counter", "text counter", "sentence counter", "reading time calculator"],
    metaTitle: "Free Word Counter - Count Words, Characters & Reading Time",
    metaDescription: "Count words, characters, sentences and reading time instantly. Free online word counter for writers, students and SEO professionals. No sign-up.",
    primaryKeyword: "word counter",
    howToUse: ["Type or paste your text into the text area above.", "View real-time counts for words, characters, sentences, and paragraphs.", "Check the keyword density section to see your most used words.", "Use the reading time estimate to plan your content."],
    faq: [
      { question: "How does the word counter count words?", answer: "The word counter splits your text by whitespace and counts each group as one word. It handles multiple spaces, tabs, and line breaks correctly." },
      { question: "How is reading time calculated?", answer: "Reading time is estimated based on an average reading speed of 200 words per minute, which is the standard for adult readers." },
      { question: "Does the word counter count numbers?", answer: "Yes, any group of characters separated by spaces is counted as a word, including numbers and mixed alphanumeric strings." },
    ],
  },
  {
    id: "character-counter",
    name: "Character Counter",
    shortName: "Char Count",
    description: "Count characters, analyze frequency, and get detailed text composition stats.",
    longDescription: "Count characters with and without spaces, analyze character frequency distribution, and get a detailed breakdown of your text composition including letters, numbers, spaces, and special characters. Perfect for Twitter/X posts, SMS messages, meta descriptions, and any content with character limits.",
    category: "text",
    icon: TextCursorInput,
    keywords: ["character counter", "letter counter", "character count", "text analysis", "character frequency", "char counter", "text composition"],
    metaTitle: "Free Character Counter - Count Characters & Analyze Text",
    metaDescription: "Count characters, analyze frequency and get text composition stats instantly. Free online character counter for social media, SMS and SEO. No sign-up.",
    primaryKeyword: "character counter",
    howToUse: ["Type or paste your text into the text area.", "View real-time character counts including total, without spaces, and unique characters.", "Check the character density breakdown to see letters, numbers, spaces, and special characters.", "Review the top 10 most-used characters with frequency percentages."],
    faq: [
      { question: "What's the difference between characters with and without spaces?", answer: "Characters with spaces counts every single character including spaces, tabs, and line breaks. Characters without spaces excludes all whitespace, giving you the count of actual visible characters." },
      { question: "How is character frequency calculated?", answer: "Each unique character in your text is counted and ranked by frequency. The tool shows the top 10 most-used characters along with their count and percentage of total characters." },
      { question: "Why would I use a character counter instead of a word counter?", answer: "Character counters are essential when you have character limits — like Twitter (280 chars), SMS (160 chars), meta descriptions (160 chars), or file naming limits. Word counters can't tell you if you're within these limits." },
    ],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    shortName: "Password Gen",
    description: "Generate strong, secure passwords with customizable options.",
    longDescription: "Generate strong, secure, and random passwords instantly. Customize length, include uppercase, lowercase, numbers, and special characters. Check password strength in real-time. Perfect for creating secure passwords for all your online accounts.",
    category: "dev",
    icon: Shield,
    keywords: ["password generator", "strong password", "secure password", "random password", "password maker", "create password"],
    metaTitle: "Free Password Generator - Create Strong Secure Passwords",
    metaDescription: "Generate strong, secure passwords instantly. Customize length and characters. Check password strength. Free online tool, no data stored.",
    primaryKeyword: "password generator",
    howToUse: ["Adjust the password length using the slider (4 to 64 characters).", "Toggle character types: uppercase, lowercase, numbers, and symbols.", "Click 'Generate New Password' to create a fresh password.", "Click the copy icon to copy the password to your clipboard."],
    faq: [
      { question: "Are the generated passwords truly random?", answer: "Yes, we use the Web Crypto API (crypto.getRandomValues) which provides cryptographically secure random numbers." },
      { question: "How long should my password be?", answer: "We recommend at least 12 characters for strong security. Longer passwords with mixed character types are significantly harder to crack." },
      { question: "Are my passwords stored anywhere?", answer: "No. Passwords are generated entirely in your browser and are never sent to any server. Once you navigate away, the password is gone." },
    ],
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    shortName: "BMI Calc",
    description: "Calculate your Body Mass Index and see your health category.",
    longDescription: "Calculate your Body Mass Index (BMI) quickly and accurately. Enter your height and weight to find out if you're underweight, normal weight, overweight, or obese. Includes BMI chart and health category explanations for better understanding of your results.",
    category: "math",
    icon: Heart,
    keywords: ["bmi calculator", "body mass index", "bmi checker", "healthy weight", "bmi chart", "weight calculator"],
    metaTitle: "Free BMI Calculator - Calculate Body Mass Index Online",
    metaDescription: "Calculate your BMI instantly with metric or imperial units. Free online BMI calculator with health categories and visual chart. No sign-up required.",
    primaryKeyword: "BMI calculator",
    howToUse: ["Select your preferred unit system (Metric or Imperial).", "Enter your weight and height in the fields provided.", "Click 'Calculate BMI' to see your results.", "Review the BMI scale and health category for context."],
    faq: [
      { question: "What is a healthy BMI range?", answer: "A BMI between 18.5 and 24.9 is considered normal weight. Below 18.5 is underweight, 25-29.9 is overweight, and 30 or above is classified as obese." },
      { question: "Is BMI accurate for everyone?", answer: "BMI is a useful screening tool but has limitations. It doesn't account for muscle mass, bone density, age, sex, or body composition. Athletes may have a high BMI due to muscle mass." },
      { question: "How is BMI calculated?", answer: "BMI is calculated by dividing your weight in kilograms by the square of your height in meters: BMI = weight (kg) / height (m) squared." },
    ],
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    shortName: "Percentage",
    description: "Calculate percentages, percentage change, and percentage difference.",
    longDescription: "Calculate any percentage easily with multiple calculation modes. Find what percent of a number is, calculate percentage increase or decrease, and find the percentage difference between two numbers. Essential for students, business owners, and financial calculations.",
    category: "math",
    icon: Percent,
    keywords: ["percentage calculator", "percent calculator", "percentage increase", "percentage decrease", "percent of", "calculate percentage"],
    metaTitle: "Free Percentage Calculator - Calculate Percentages Instantly",
    metaDescription: "Calculate percentages, increase, decrease and change instantly. Free online percentage calculator for students, business and finance. Works in browser.",
    primaryKeyword: "percentage calculator",
    howToUse: ["Choose a calculation mode: '% of Number', '% of What?', or '% Change'.", "Enter your numbers in the input fields.", "Click 'Calculate' to see the result instantly.", "Use the common examples below for quick reference."],
    faq: [
      { question: "How do I calculate percentage increase?", answer: "Use the '% Change' tab. Enter the original value in 'From' and the new value in 'To'. The calculator shows the percentage increase or decrease." },
      { question: "What is 10% of 500?", answer: "10% of 500 is 50. You can verify this using the '% of Number' tab: enter 10 in the percentage field and 500 in the number field." },
      { question: "How do I calculate what percentage one number is of another?", answer: "Use the '% of What?' tab. Enter the part in the first field and the whole in the second field. For example, 50 is 25% of 200." },
    ],
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    shortName: "Age Calc",
    description: "Calculate your exact age in years, months, and days.",
    longDescription: "Calculate your exact age in years, months, weeks, days, hours, minutes, and seconds. Simply enter your date of birth and get a detailed breakdown of your age. Also calculates days until your next birthday.",
    category: "math",
    icon: Calendar,
    keywords: ["age calculator", "calculate age", "how old am I", "age in days", "birthday calculator", "date of birth calculator"],
    metaTitle: "Free Age Calculator - Exact Age in Years, Months & Days",
    metaDescription: "Calculate your exact age in years, months, days, hours and seconds. Free online age calculator with next birthday countdown and zodiac sign.",
    primaryKeyword: "age calculator",
    howToUse: ["Enter your date of birth in the first date field.", "Optionally change the 'Age at Date' to calculate age at a specific point.", "Click 'Calculate Age' to see a detailed age breakdown.", "View your zodiac sign, day of birth, and next birthday countdown."],
    faq: [
      { question: "How accurate is the age calculator?", answer: "The age calculator is accurate to the day, accounting for leap years and varying month lengths. It shows your exact age in multiple units." },
      { question: "Does it account for leap years?", answer: "Yes, the calculator properly handles leap years when computing your exact age in days, weeks, and months." },
      { question: "Can I calculate age between two custom dates?", answer: "Yes! Change the 'Age at Date' field to any date to calculate the age difference between your birth date and that specific date." },
    ],
  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    shortName: "Loan Calc",
    description: "Calculate monthly payments, total interest, and amortization.",
    longDescription: "Calculate your monthly loan payments, total interest paid, and view a complete amortization schedule. Works for mortgages, car loans, personal loans, and any fixed-rate loan. Adjust interest rate, loan term, and principal to find the perfect loan for your budget.",
    category: "math",
    icon: Banknote,
    keywords: ["loan calculator", "mortgage calculator", "emi calculator", "monthly payment", "interest calculator", "amortization schedule"],
    metaTitle: "Free Loan Calculator - Monthly Payment & Amortization",
    metaDescription: "Calculate monthly loan payments, total interest and view amortization schedule. Free mortgage and EMI calculator. Works for any fixed-rate loan.",
    primaryKeyword: "loan calculator",
    howToUse: ["Enter the total loan amount in dollars.", "Enter the annual interest rate as a percentage (e.g., 6.5 for 6.5%).", "Enter the loan term in years.", "Click 'Calculate Payment' to see monthly payment, total cost, and full amortization schedule."],
    faq: [
      { question: "What types of loans does this calculator work for?", answer: "This calculator works for any fixed-rate loan including mortgages, car loans, personal loans, student loans, and business loans." },
      { question: "How is the monthly payment calculated?", answer: "The monthly payment is calculated using the standard amortization formula: M = P[r(1+r)^n]/[(1+r)^n-1], where P is principal, r is monthly rate, and n is total months." },
      { question: "What is an amortization schedule?", answer: "An amortization schedule shows how each monthly payment is split between principal and interest over the life of the loan, plus the remaining balance after each payment." },
    ],
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    shortName: "Unit Convert",
    description: "Convert between units of length, weight, temperature, and more.",
    longDescription: "Convert between hundreds of units across multiple categories including length, weight, temperature, volume, area, speed, time, and data. Fast, accurate, and easy to use unit conversion tool for students, professionals, and everyday use.",
    category: "math",
    icon: ArrowLeftRight,
    keywords: ["unit converter", "length converter", "weight converter", "temperature converter", "metric converter", "measurement converter"],
    metaTitle: "Free Unit Converter - Length, Weight, Temperature & More",
    metaDescription: "Convert between units of length, weight, temperature, volume, speed and data storage. Free online unit converter. Metric and imperial supported.",
    primaryKeyword: "unit converter",
    howToUse: ["Select a category (Length, Weight, Temperature, Volume, Area, Speed, or Data).", "Choose the unit you're converting from and to using the dropdowns.", "Enter a value in the 'From' field — the 'To' field updates instantly.", "Click the swap button to reverse the conversion direction."],
    faq: [
      { question: "How many unit categories are available?", answer: "There are 7 categories: Length, Weight, Temperature, Volume, Area, Speed, and Data Storage. Each category has multiple units to convert between." },
      { question: "Is the unit converter accurate?", answer: "Yes, conversions use precise mathematical factors. For example, 1 inch equals exactly 2.54 centimeters, and temperature conversions use the exact Celsius-Fahrenheit formulas." },
      { question: "Can I convert between metric and imperial?", answer: "Absolutely! The converter supports both metric (km, kg, Celsius) and imperial (miles, pounds, Fahrenheit) systems and converts between them seamlessly." },
    ],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    shortName: "Case Convert",
    description: "Convert text to uppercase, lowercase, title case, and more.",
    longDescription: "Instantly convert your text between different cases including uppercase, lowercase, title case, sentence case, camelCase, PascalCase, snake_case, and kebab-case. Perfect for developers, writers, and anyone who needs to format text quickly.",
    category: "text",
    icon: CaseSensitive,
    keywords: ["case converter", "uppercase converter", "lowercase converter", "title case", "sentence case", "text case changer"],
    metaTitle: "Free Case Converter - Uppercase, Title Case, camelCase & More",
    metaDescription: "Convert text to uppercase, lowercase, title case, camelCase, snake_case and more. Free online case converter. Copy results instantly.",
    primaryKeyword: "case converter",
    howToUse: ["Type or paste your text into the input area.", "Click any conversion button (UPPERCASE, lowercase, Title Case, etc.).", "The converted text appears in the result section below.", "Click 'Copy' to copy the converted text to your clipboard."],
    faq: [
      { question: "What is camelCase?", answer: "camelCase starts with a lowercase letter and each subsequent word starts with an uppercase letter with no spaces. Example: 'helloWorld'. Commonly used in JavaScript and Java." },
      { question: "What is the difference between Title Case and Sentence case?", answer: "Title Case capitalizes the first letter of every word (Hello World), while Sentence case only capitalizes the first letter of the sentence (Hello world)." },
      { question: "What is snake_case used for?", answer: "snake_case uses underscores between words with all lowercase letters (hello_world). It's commonly used in Python, Ruby, and database column names." },
    ],
  },
  {
    id: "color-picker",
    name: "Color Picker",
    shortName: "Color Pick",
    description: "Pick colors and convert between HEX, RGB, and HSL formats.",
    longDescription: "Pick any color and instantly get its values in HEX, RGB, HSL, and CMYK formats. Use the color wheel or input specific values. Generate color palettes and find complementary colors. Essential tool for designers, developers, and artists.",
    category: "dev",
    icon: Palette,
    keywords: ["color picker", "hex color", "rgb color", "hsl color", "color converter", "color palette generator"],
    metaTitle: "Free Color Picker - HEX, RGB, HSL Converter & Palette Tool",
    metaDescription: "Pick colors and convert between HEX, RGB, HSL formats instantly. Free online color picker with palette generator for designers and developers.",
    primaryKeyword: "color picker",
    howToUse: ["Use the HEX input to enter a color code directly, or adjust the RGB/HSL sliders.", "Click any color value (HEX, RGB, HSL) to copy it to your clipboard.", "View color variations: lighter, darker, and complementary colors.", "Use the generated palette at the bottom for shading inspiration."],
    faq: [
      { question: "What is the difference between HEX and RGB?", answer: "HEX is a hexadecimal color code (e.g., #FF5733) commonly used in web design. RGB represents color as three numbers (e.g., 255, 87, 51) representing red, green, and blue intensity." },
      { question: "What is HSL color format?", answer: "HSL stands for Hue (0-360 degrees on the color wheel), Saturation (0-100% intensity), and Lightness (0-100% brightness). It's more intuitive for adjusting colors." },
      { question: "How do I find a complementary color?", answer: "A complementary color is automatically calculated and shown in the Color Variations section. It's the color directly opposite on the color wheel, creating high contrast." },
    ],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    shortName: "JSON Format",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    longDescription: "Format, validate, and beautify your JSON data instantly. Paste messy JSON and get perfectly formatted, indented output with syntax highlighting. Includes error detection, JSON minification, and tree view. Essential tool for developers working with APIs and data.",
    category: "dev",
    icon: Braces,
    keywords: ["json formatter", "json beautifier", "json validator", "json viewer", "format json", "pretty print json"],
    metaTitle: "Free JSON Formatter & Validator - Beautify JSON Online",
    metaDescription: "Format, validate and beautify JSON instantly with syntax highlighting. Free online JSON formatter with tree view and minifier. 100% private.",
    primaryKeyword: "JSON formatter",
    howToUse: ["Paste your JSON data into the input text area, or click 'Upload .json' to load a file.", "Click 'Format / Beautify' to pretty-print the JSON with proper indentation.", "Click 'Minify' to compress JSON to a single line.", "Click 'Validate' to check if your JSON is valid without reformatting."],
    faq: [
      { question: "What is JSON?", answer: "JSON (JavaScript Object Notation) is a lightweight data-interchange format that's easy for humans to read and write, and easy for machines to parse and generate. It's used widely in APIs and configuration files." },
      { question: "Why is my JSON showing an error?", answer: "Common JSON errors include missing commas between items, trailing commas (not allowed in JSON), unquoted keys, and single quotes instead of double quotes. The error message will tell you exactly where the problem is." },
      { question: "Is my JSON data sent to a server?", answer: "No. All JSON processing happens entirely in your browser. Your data is never transmitted to any external server, ensuring complete privacy." },
    ],
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    shortName: "Image Compress",
    description: "Compress and resize images right in your browser. Supports JPEG, PNG, WebP.",
    longDescription: "Compress and resize images directly in your browser without uploading to any server. Adjust quality, change dimensions, and convert between JPEG, PNG, and WebP formats. See instant file size comparison before downloading. Perfect for optimizing images for web, email, and social media.",
    category: "image",
    icon: ImageDown,
    keywords: ["image compressor", "compress image", "resize image", "reduce image size", "image optimizer", "jpeg compressor", "png compressor", "webp converter"],
    metaTitle: "Free Image Compressor - Compress JPEG, PNG, WebP Online",
    metaDescription: "Compress and resize images online for free. Reduce file size up to 90%. Convert between JPEG, PNG and WebP. 100% private, all processing in your browser.",
    primaryKeyword: "image compressor",
    howToUse: ["Click or drag and drop an image file into the upload area.", "Adjust the quality slider and optionally set max width/height.", "Choose your preferred output format (JPEG, PNG, or WebP).", "Click 'Download Compressed Image' to save the optimized file."],
    faq: [
      { question: "Does image compression reduce quality?", answer: "Yes, lossy compression (JPEG, WebP) reduces file size by removing some image data. You control the quality level — higher quality means less compression. PNG is lossless and preserves full quality." },
      { question: "What image formats are supported?", answer: "You can upload JPEG, PNG, WebP, GIF, and BMP images. Output formats available are JPEG, PNG, and WebP." },
      { question: "Is my image uploaded to a server?", answer: "No. All compression happens entirely in your browser using the HTML5 Canvas API. Your images never leave your device." },
    ],
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    shortName: "QR Code",
    description: "Generate customizable QR codes from text or URLs. Download as PNG.",
    longDescription: "Generate QR codes instantly from any text, URL, email address, phone number, or WiFi credentials. Customize size, colors, and download as a high-quality PNG image. Perfect for business cards, marketing materials, and sharing links.",
    category: "dev",
    icon: QrCode,
    keywords: ["qr code generator", "create qr code", "qr code maker", "free qr code", "qr code online", "generate qr", "custom qr code"],
    metaTitle: "Free QR Code Generator - Create Custom QR Codes Online",
    metaDescription: "Generate free QR codes from text or URLs. Customize colors and size. Download as PNG. No sign-up required, 100% free.",
    primaryKeyword: "QR code generator",
    howToUse: ["Enter your text or URL in the input field.", "Customize the QR code size using the slider.", "Optionally change the foreground and background colors.", "Click 'Download PNG' or 'Copy to Clipboard' to save your QR code."],
    faq: [
      { question: "What can I encode in a QR code?", answer: "You can encode any text — URLs, email addresses, phone numbers, WiFi credentials, vCard contact info, or plain text. The QR code reader will interpret it accordingly." },
      { question: "Is there a limit to QR code content length?", answer: "Yes. A standard QR code can hold up to about 4,296 alphanumeric characters or 7,089 numeric digits. Longer content results in denser QR codes that may be harder to scan." },
      { question: "Can I change the QR code colors?", answer: "Yes! You can customize both the foreground (dark) and background (light) colors. For best scanability, ensure there's good contrast between the two colors." },
    ],
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    shortName: "Base64",
    description: "Encode text or files to Base64, or decode Base64 back to text or files.",
    longDescription: "Encode text to Base64 or decode Base64 strings back to text. Also supports encoding files to Base64 data URIs and decoding Base64 back to downloadable files. Essential tool for developers working with data URIs, API payloads, and binary data in text format.",
    category: "dev",
    icon: Binary,
    keywords: ["base64 encoder", "base64 decoder", "encode base64", "decode base64", "base64 converter", "file to base64", "base64 to file"],
    metaTitle: "Free Base64 Encoder/Decoder - Text & File Conversion",
    metaDescription: "Encode text or files to Base64 and decode Base64 back. Supports Unicode text, file uploads, and data URI conversion. Free online tool.",
    primaryKeyword: "base64 encoder",
    howToUse: ["Switch to the 'Encode' tab to convert text or files to Base64.", "Switch to the 'Decode' tab to convert Base64 back to text or a file.", "Paste your input or upload a file, then click the action button.", "Copy the result or download the decoded file."],
    faq: [
      { question: "What is Base64 encoding?", answer: "Base64 is a binary-to-text encoding scheme that represents binary data using 64 ASCII characters. It's commonly used to embed images in HTML/CSS, send binary data in JSON, and encode email attachments." },
      { question: "Does it support Unicode characters?", answer: "Yes. The encoder handles Unicode text (including emojis and non-Latin scripts) by first converting to UTF-8 bytes before Base64 encoding." },
      { question: "Can I encode files to Base64?", answer: "Yes. Use the 'Upload File' button on the Encode tab. The file will be converted to a Base64 data URI string that you can use in HTML, CSS, or API calls." },
    ],
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    shortName: "URL Encode",
    description: "Encode and decode URLs with automatic URL component breakdown.",
    longDescription: "Encode special characters in URLs for safe transmission, or decode percent-encoded URLs back to readable text. Includes automatic URL breakdown showing scheme, host, path, query parameters, and fragment. Essential for web developers working with APIs and web addresses.",
    category: "dev",
    icon: Link,
    keywords: ["url encoder", "url decoder", "encode url", "decode url", "percent encoding", "url encode online", "urlencode"],
    metaTitle: "Free URL Encoder/Decoder - Percent Encoding Tool",
    metaDescription: "Encode and decode URLs instantly. See automatic URL breakdown with scheme, host, path and query params. Free online tool for developers.",
    primaryKeyword: "URL encoder",
    howToUse: ["Switch to 'Encode' tab to encode special characters in a URL.", "Switch to 'Decode' tab to decode a percent-encoded URL.", "Paste your URL and click the action button.", "View the URL breakdown panel to see parsed components."],
    faq: [
      { question: "When should I URL-encode a string?", answer: "URL-encode whenever you need to include special characters (spaces, &, =, ?, #, etc.) in a URL query parameter or path segment. This ensures the URL is properly transmitted and parsed." },
      { question: "What is percent encoding?", answer: "Percent encoding replaces unsafe ASCII characters with a '%' followed by two hexadecimal digits. For example, a space becomes '%20' and '&' becomes '%26'." },
      { question: "What is the difference between encodeURI and encodeURIComponent?", answer: "encodeURI encodes characters that are not allowed in a full URL but leaves URL structure characters (:, /, ?, &, =) intact. encodeURIComponent encodes ALL special characters including these, making it suitable for individual query parameter values." },
    ],
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    shortName: "Lorem Ipsum",
    description: "Generate placeholder text in paragraphs, sentences, or words.",
    longDescription: "Generate lorem ipsum placeholder text for your designs, mockups, and prototypes. Choose the number of paragraphs, sentences, or words. Option to start with the classic 'Lorem ipsum dolor sit amet' opening. Perfect for designers, developers, and content creators.",
    category: "text",
    icon: FileText,
    keywords: ["lorem ipsum generator", "placeholder text", "dummy text", "filler text", "lorem ipsum", "sample text generator", "mockup text"],
    metaTitle: "Free Lorem Ipsum Generator - Placeholder Text Tool",
    metaDescription: "Generate lorem ipsum placeholder text by paragraphs, sentences or words. Customizable count and options. Copy instantly. Free online tool.",
    primaryKeyword: "lorem ipsum generator",
    howToUse: ["Select the type: Paragraphs, Sentences, or Words.", "Set the count using the number input.", "Toggle 'Start with Lorem ipsum dolor sit amet' if desired.", "Click 'Copy All' to copy the generated text to your clipboard."],
    faq: [
      { question: "What is lorem ipsum?", answer: "Lorem ipsum is placeholder text used in printing, graphic design, and web development. It's derived from a 1st-century BC Latin text by Cicero and has been the industry standard for placeholder text since the 1500s." },
      { question: "Is lorem ipsum readable Latin?", answer: "Not quite. While it's based on real Latin words from Cicero's De Finibus, the text has been scrambled and altered over centuries, so it's not grammatically correct Latin." },
      { question: "Can I customize the amount of text?", answer: "Yes. You can generate text by paragraphs (1-20), sentences (1-50), or words (1-500). The text regenerates instantly as you adjust the settings." },
    ],
  },
  {
    id: "markdown-previewer",
    name: "Markdown Previewer",
    shortName: "Markdown",
    description: "Write Markdown and see a live HTML preview with split-view editor.",
    longDescription: "Write Markdown in a split-view editor and see a live HTML preview in real time. Supports full GitHub Flavored Markdown including tables, code blocks with syntax highlighting, task lists, and more. Copy the rendered HTML output. Perfect for writing README files, documentation, and blog posts.",
    category: "text",
    icon: AlignLeft,
    keywords: ["markdown previewer", "markdown editor", "markdown to html", "markdown viewer", "online markdown", "gfm previewer", "markdown live preview"],
    metaTitle: "Free Markdown Previewer - Live Editor with HTML Export",
    metaDescription: "Write Markdown and see live HTML preview instantly. Supports GFM, tables, code blocks. Copy HTML output. Free online tool, no sign-up.",
    primaryKeyword: "markdown previewer",
    howToUse: ["Type or paste Markdown in the left editor panel.", "See the rendered HTML preview on the right in real time.", "Switch between Split, Preview, and HTML Source views.", "Click 'Copy HTML' to copy the rendered HTML to your clipboard."],
    faq: [
      { question: "What Markdown features are supported?", answer: "The previewer supports GitHub Flavored Markdown (GFM) including headings, bold, italic, links, images, code blocks, tables, task lists, blockquotes, and horizontal rules." },
      { question: "Can I export the HTML output?", answer: "Yes. Click the 'Copy HTML' button to copy the rendered HTML to your clipboard. You can then paste it into a CMS, email, or HTML file." },
      { question: "Does it support syntax highlighting for code blocks?", answer: "Code blocks are styled with proper formatting and background colors. Full syntax highlighting for specific languages requires additional libraries, but the code blocks are clearly formatted and readable." },
    ],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    shortName: "Hash Gen",
    description: "Generate SHA-1, SHA-256, and SHA-512 hashes from any text.",
    longDescription: "Generate cryptographic hashes from any text input using the Web Crypto API. Supports SHA-1, SHA-256, and SHA-512 algorithms. Real-time hashing as you type with one-click copy for each hash. Essential for verifying file integrity, storing passwords securely, and generating checksums.",
    category: "dev",
    icon: Lock,
    keywords: ["hash generator", "sha256", "sha512", "sha1", "hash calculator", "cryptographic hash", "checksum generator", "hash online"],
    metaTitle: "Free Hash Generator - SHA-1, SHA-256, SHA-512 Online",
    metaDescription: "Generate SHA-1, SHA-256 and SHA-512 hashes from any text instantly. Uses Web Crypto API. Free online tool, 100% private.",
    primaryKeyword: "hash generator",
    howToUse: ["Enter or paste your text in the input field.", "View the generated hashes for SHA-1, SHA-256, and SHA-512 below.", "Click the copy icon next to any hash to copy it.", "Hashes update in real time as you type (debounced)."],
    faq: [
      { question: "Which hash algorithm should I use?", answer: "SHA-256 is recommended for most purposes — it offers a good balance of security and performance. SHA-512 provides even stronger security. SHA-1 is considered weak and should only be used for compatibility with legacy systems." },
      { question: "How are the hashes generated?", answer: "Hashes are generated using the Web Crypto API built into your browser. This uses the same cryptographic libraries that browsers use for HTTPS/TLS connections, ensuring high-quality, standards-compliant hash generation." },
      { question: "Is my text sent to a server?", answer: "No. All hashing happens entirely in your browser using the Web Crypto API. Your input text is never transmitted to any external server." },
    ],
  },
  {
    id: "number-base-converter",
    name: "Number Base Converter",
    shortName: "Base Convert",
    description: "Convert between binary, octal, decimal, and hexadecimal number systems.",
    longDescription: "Convert numbers between binary (base 2), octal (base 8), decimal (base 10), and hexadecimal (base 16) instantly. Supports large numbers using BigInt for arbitrary precision. Perfect for computer science students, programmers, and anyone working with different number systems.",
    category: "math",
    icon: Hash,
    keywords: ["number base converter", "binary converter", "hex converter", "decimal to binary", "hex to decimal", "octal converter", "radix converter"],
    metaTitle: "Free Number Base Converter - Binary, Hex, Octal, Decimal",
    metaDescription: "Convert between binary, octal, decimal and hexadecimal instantly. Supports large numbers with BigInt. Free online tool for programmers and students.",
    primaryKeyword: "number base converter",
    howToUse: ["Select your input base (Binary, Octal, Decimal, or Hexadecimal).", "Enter your number in the input field.", "See the conversion results in all other bases instantly.", "Click any swap button to use a result as your new input."],
    faq: [
      { question: "What is binary?", answer: "Binary (base 2) is a number system using only 0 and 1. It's the fundamental language of computers — all data is ultimately represented as binary digits (bits)." },
      { question: "What is hexadecimal?", answer: "Hexadecimal (base 16) uses digits 0-9 and letters A-F. It's commonly used in programming to represent memory addresses, color codes (#FF5733), and binary data in a more compact form." },
      { question: "Does it support large numbers?", answer: "Yes. The converter uses JavaScript's BigInt for arbitrary-precision arithmetic, so it can handle numbers of any size without loss of precision." },
    ],
  },
  {
    id: "text-diff-checker",
    name: "Text Diff Checker",
    shortName: "Text Diff",
    description: "Compare two texts and highlight added, removed, and unchanged lines.",
    longDescription: "Compare two pieces of text side by side and instantly see the differences. Added lines are highlighted in green, removed lines in red, and unchanged lines in gray. Shows statistics for lines added, removed, and unchanged. Perfect for comparing code revisions, document versions, and text changes.",
    category: "dev",
    icon: Diff,
    keywords: ["text diff", "compare text", "text difference", "diff checker", "text comparison", "compare two texts", "find differences"],
    metaTitle: "Free Text Diff Checker - Compare Two Texts Online",
    metaDescription: "Compare two texts and see differences highlighted instantly. Shows added, removed and unchanged lines with statistics. Free online diff tool.",
    primaryKeyword: "text diff checker",
    howToUse: ["Paste your original text in the left textarea.", "Paste the modified text in the right textarea.", "Click 'Compare' to see the differences highlighted.", "Review the stats showing lines added, removed, and unchanged."],
    faq: [
      { question: "How does the diff comparison work?", answer: "The tool performs a line-by-line comparison between the two texts. Lines present only in the original are marked as removed, lines only in the modified text are marked as added, and matching lines are marked as unchanged." },
      { question: "Is it case-sensitive?", answer: "Yes, the comparison is case-sensitive. 'Hello' and 'hello' are treated as different lines." },
      { question: "Can I compare code files?", answer: "Absolutely. The diff checker works with any text, including source code, configuration files, and plain text. Simply paste the code from both versions into the textareas." },
    ],
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    shortName: "PDF Compress",
    description: "Compress PDF files in your browser. Reduce file size with three compression levels.",
    longDescription: "Compress PDF files directly in your browser without uploading to any server. Choose from three compression levels — Low (structural optimization), Medium (metadata stripping), or High (image re-encoding). See the file size reduction before downloading. Perfect for reducing PDF sizes for email attachments and web uploads.",
    category: "image",
    icon: FileDown,
    keywords: ["pdf compressor", "compress pdf", "reduce pdf size", "pdf optimizer", "pdf compression", "make pdf smaller", "online pdf compressor"],
    metaTitle: "Free PDF Compressor - Reduce PDF File Size Online",
    metaDescription: "Compress PDF files online for free. Three compression levels. No upload needed — all processing in your browser. Reduce PDF size by up to 80%.",
    primaryKeyword: "PDF compressor",
    howToUse: ["Click or drag and drop a PDF file into the upload area.", "Select your compression level (Low, Medium, or High).", "Click 'Compress PDF' and wait for processing.", "Download the compressed PDF and check the size reduction."],
    faq: [
      { question: "How does PDF compression work?", answer: "Low level removes unused objects. Medium level also strips metadata (author, title, etc.). High level additionally re-encodes embedded images at lower quality for maximum file size reduction." },
      { question: "Will compression affect PDF quality?", answer: "Low and Medium levels preserve all visual content. High level may reduce image quality within the PDF. Text, vector graphics, and layout are always preserved regardless of compression level." },
      { question: "Is my PDF uploaded to a server?", answer: "No. All compression happens entirely in your browser using client-side JavaScript. Your PDF files never leave your device, ensuring complete privacy and security." },
    ],
  },
];